### ISSUE TITLE
Module 'cipheydists' has no attribute 'get_lists'

### ISSUE THREAD

**Issue by brandonskerritt** [Ciphey/Ciphey#103]
```
➜ python3 ciphey -t "LHFKM"
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "ciphey/__main__.py", line 391, in <module>
    main(withArgs=True)
  File "ciphey/__main__.py", line 366, in main
    output = call_encryption(**result)
  File "ciphey/__main__.py", line 383, in call_encryption
    cipher_obj = Ciphey(text, greppable, Cipher, debug)
  File "ciphey/__main__.py", line 46, in __init__
    self.lc = lc.LanguageChecker()
  File "/home/bee/.local/lib/python3.8/site-packages/ciphey/languageCheckerMod/LanguageChecker.py", line 64, in __init__
    self.dictionary = dc.dictionaryChecker()
  File "ciphey/languageCheckerMod/dictionaryChecker.py", line 34, in __init__
    self.top1000Words = dict.fromkeys(cipheydists.get_list("english1000"))
AttributeError: module 'cipheydists' has no attribute 'get_list'
```

**Comment by brandonskerritt** [comment]
nvm i wasnt in virtual env
