### ISSUE TITLE
Binary Bug

### ISSUE THREAD

**Issue by brandonskerritt** [Ciphey/Ciphey#114]
This is 2 bugs in one, but both relate to binary
```➜ ciphey -t "01101000 01100101 01101100 01101100 01101111 00100000 01101100 01100101 01110100 00100111 01110011 00100000 01100010 01101001 01101110 01100001 01110010 01111001"
┏━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┓
┃ Name of Cipher ┃ Probability ┃
┡━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━┩
│ Reverse        │      100.0% │
└────────────────┴─────────────┘
Traceback (most recent call last):
  File "/home/bee/.local/bin/ciphey", line 8, in <module>
    sys.exit(main())
  File "/home/bee/.local/lib/python3.8/site-packages/ciphey/__main__.py", line 302, in main
    cipherObj.decrypt()
  File "/home/bee/.local/lib/python3.8/site-packages/ciphey/__main__.py", line 128, in decrypt
    self.one_level_of_decryption()
  File "/home/bee/.local/lib/python3.8/site-packages/ciphey/__main__.py", line 185, in one_level_of_decryption
    self.decryptNormal()
  File "/home/bee/.local/lib/python3.8/site-packages/ciphey/__main__.py", line 193, in decryptNormal
    ret = key.decrypt(self.text)
  File "/home/bee/.local/lib/python3.8/site-packages/ciphey/Decryptor/Encoding/encodingParent.py", line 40, in decrypt
    self.lc = self.lc + answer["lc"]
TypeError: 'NoneType' object is not subscriptable```
**I cannot recreate the original issue since I re-installed ciphey, but the comments still remain important**.

**Comment by brandonskerritt** [comment]
![E1UHt5IqyD0Y](https://user-images.githubusercontent.com/10378052/84330286-e423c580-ab7e-11ea-9d6f-84225d362913.png)

Bug from @szymex73

**Comment by bee-san** [comment]
I can reproduce this, even in grep mode. 
```
➜ ciphey -t "01101100 01100101 01110100 01110011 00100000 01110100 01110010 01111001 00100000 01110011 01101111 01101101 01100101 00100000 01100010 01101001 01101110 01100001 01110010 01111001 00100000 01101111 01110101 01110100 00100001" -g
lets try some binary out!
{'lc': <ciphey.LanguageChecker.autumn.Autumn object at 0x7fd210390190>, 'IsPlaintext?': True, 'Plaintext': 'lets try some binary out!', 'Cipher': 'Ascii to Binary encoded', 'Extra Information': None}```

**Comment by bee-san** [comment]
```
2020-06-11 01:24:20.718 | DEBUG    | ciphey.__main__:decrypt_normal:282 - Ret is plaintext
lets try some binary out!
2020-06-11 01:24:20.718 | DEBUG    | ciphey.__main__:decrypt:182 - decrypt is outputting {'lc': <ciphey.LanguageChecker.autumn.Autumn object at 0x7f3763045d00>, 'IsPlaintext?': True, 'Plaintext': 'lets try some binary out!', 'Cipher': 'Ascii to Binary encoded', 'Extra Information': None}
{'lc': <ciphey.LanguageChecker.autumn.Autumn object at 0x7f3763045d00>, 'IsPlaintext?': True, 'Plaintext': 'lets try some binary out!', 'Cipher': 'Ascii to Binary encoded', 'Extra Information': None}
``` useful debug info

**Comment by brandonskerritt** [comment]
I will fix this!

**Comment by brandonskerritt** [comment]
fixed it
