### ISSUE TITLE
AuSearch could not find any solutions

### ISSUE THREAD

**Issue by brandonskerritt** [Ciphey/Ciphey#163]
```
➜ poetry run ciphey -t "aGVsbG8gbXkgbmFtZSB"         
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bee/.cache/pypoetry/virtualenvs/ciphey-MhwK4__h-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/bee/.cache/pypoetry/virtualenvs/ciphey-MhwK4__h-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/bee/.cache/pypoetry/virtualenvs/ciphey-MhwK4__h-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bee/.cache/pypoetry/virtualenvs/ciphey-MhwK4__h-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/bee/Documents/Ciphey/ciphey/__main__.py", line 250, in main
    print(decrypt(config, kwargs["text"]))
  File "/home/bee/Documents/Ciphey/ciphey/__main__.py", line 40, in decrypt
    res: iface.SearchResult = config.objs["searcher"].search(ctext)
  File "/home/bee/Documents/Ciphey/ciphey/basemods/Searchers/ausearch.py", line 162, in search
    raise LookupError("Could not find any solutions")
LookupError: Could not find any solutions
```

Can we get something nicer?

**Comment by Cyclic3** [comment]
This is so sad. Can we hit 50 pull requests?

Maybe I could make the `Searcher` interface return `Optional[...]` so that we could handle this more pleasantly?

_This specific error can actually be fixed if we filter out empty strings from the autumn checker (would recommend)_

**Comment by brandonskerritt** [comment]
This is fixed
