### ISSUE TITLE
No Module Named 'Decryptor'

### ISSUE THREAD

**Issue by timshane** [Ciphey/Ciphey#218]
Receive the following error when attempting to run ciphey on macOS Catalina: 

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ciphey/Decryptor/basicEncryption/basic_parent.py", line 11, in <module>
    import Decryptor.basicEncryption.caesar as ca
ModuleNotFoundError: No module named 'Decryptor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/ciphey", line 5, in <module>
    from ciphey.__main__ import main
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ciphey/__main__.py", line 47, in <module>
    from ciphey.Decryptor.basicEncryption.basic_parent import BasicParent
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ciphey/Decryptor/basicEncryption/basic_parent.py", line 17, in <module>
    import ciphey.Decryptor.basicEncryption.caesar as ca
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ciphey/Decryptor/basicEncryption/caesar.py", line 11, in <module>
    import cipheycore
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cipheycore/__init__.py", line 13, in <module>
    from . import _ciphey_core_py
ImportError: cannot import name '_ciphey_core_py' from partially initialized module 'cipheycore' (most likely due to a circular import) (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cipheycore/__init__.py)

**Comment by brandonskerritt** [comment]
Hey! This is caused by the current version of Ciphey.

Please use the latest version
```
pip3 install ciphey==5.0.0rc10
```

**Comment by Cyclic3** [comment]
Just an addendum: we are planning to properly release this version tomorrow, which should mean that this never happens again
