### ISSUE TITLE
Hex decoder doesn't work

### ISSUE THREAD

**Issue by brandonskerritt** [Ciphey/Ciphey#219]
On latest version with file input:

```python
python3 -m ciphey - activation.txt
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/kiyoukan/.local/lib/python3.8/site-packages/ciphey/main.py", line 3, in <module>
    ciphey.main()
  File "/home/kiyoukan/.local/lib/python3.8/site-packages/click/core.py", line 829, in call
    return self.main(args, kwargs)
  File "/home/kiyoukan/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/kiyoukan/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, ctx.params)
  File "/home/kiyoukan/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(args, **kwargs)
  File "/home/kiyoukan/.local/lib/python3.8/site-packages/ciphey/ciphey.py", line 255, in main
    kwargs["text"] = kwargs["file_stdin"].read().decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf7 in position 8: invalid start byte
```
[test.txt](https://github.com/Ciphey/Ciphey/files/5001605/test.txt)

**Comment by Cyclic3** [comment]
That snippet in main should check if the user has requested binary input

**Comment by Cyclic3** [comment]
This file doesn't seem to have any hex in it! I'm closing until some expected behaviour can be found
