### ISSUE TITLE
Encountered TypeError when decrypting long input

### ISSUE THREAD

**Issue by lukasgabriel** [Ciphey/Ciphey#248]
**Traceback:**
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\lukas\AppData\Local\pypoetry\Cache\virtualenvs\ciphey-xvyT1_eU-py3.7\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\lukas\AppData\Local\pypoetry\Cache\virtualenvs\ciphey-xvyT1_eU-py3.7\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\lukas\AppData\Local\pypoetry\Cache\virtualenvs\ciphey-xvyT1_eU-py3.7\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\lukas\AppData\Local\pypoetry\Cache\virtualenvs\ciphey-xvyT1_eU-py3.7\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\lukas\Documents\GitHub\Ciphey\ciphey\ciphey.py", line 277, in main
    result = decrypt(config, kwargs["text"])
  File "C:\Users\lukas\Documents\GitHub\Ciphey\ciphey\ciphey.py", line 40, in decrypt
    res: Optional[iface.SearchResult] = config.objs["searcher"].search(ctext)
  File "C:\Users\lukas\Documents\GitHub\Ciphey\ciphey\basemods\Searchers\ausearch.py", line 214, in search
    check_res = self._config().objs["checker"](ctext)
  File "C:\Users\lukas\Documents\GitHub\Ciphey\ciphey\iface\_modules.py", line 116, in __call__
    return self.check(*args)
  File "C:\Users\lukas\Documents\GitHub\Ciphey\ciphey\basemods\Checkers\ezcheck.py", line 19, in check
    res = checker.check(text)
  File "C:\Users\lukas\Documents\GitHub\Ciphey\ciphey\basemods\Checkers\brandon.py", line 224, in check
    length_text, self.thresholds_phase1.keys()
  File "C:\Users\lukas\Documents\GitHub\Ciphey\ciphey\basemods\Checkers\brandon.py", line 277, in calculateWhatChecker
    what_to_use = key[_keys[-1]]
TypeError: 'dict_keys' object is not subscriptable
```

**Input used:**
``` 
poetry run ciphey -v -t "R hvv blf tzgsvi yvuliv nv...sfmtib...gviirurvw... Xofgxsrmt blfi yzyvh gl blfi yivzhg. Vnkvili Vnsbi srh nzixsvw srh ovtrlmh rmgl lfi ozmwh... Ozrw hrvtv gl vevib uligivhh uiln sviv gl gsv Yofv Nlfmgzrmh. Izyrw zmw izevmlfh, sv yrgvh zmw yrgvh zdzb. Nvm lu gsv Mligs, blf hgzmw zg gsv kivxrkrxv. Blfi prmth szev uzrovw blf, hl mld blf gfim gl gsv tlwh! Zmw bvg blf wl mlg kovzw? Blf wl mlg pmvvo gl wfhg blfi svzwh drgs zhs? Rmhgvzw blf dzro,  Dsb szev gsv tlwh ulihzpvm fh?  Dv nfhg ollp rmgl gsv girzoh dv uzrovw olmt ztl! Rm z grnv kzhhvw, lfi dliow rmgvigdrmvw drgs zmlgsvi gsilfts zm fksvzezo hxslozih xzoo gsv Xlmqfmxgrlm lu gsv Hksvivh... Gsv tlwh zooldvw fmslob ulixvh gl hork rmgl lfi wlnzrm. Gsv luuhkirmt lu gszg xzgzxobhn dzh gsv mvuvirlfh ulixv xzoovw nztrx... Bvg dv wrw mlg yzmrhs rg, rmhgvzw hgfwbrmt gsv erov zixzmv uli lfi kldvi zmw dvzogs! Zmw gsv nlmhgvih zg lfi wlli...gsv fmslob ivorxgh lu gsrh Xlmqfmxgrlm? ...gsv gilooh...gsv xlikhv vzgvih...gsv dvivdloevh? Wrw dv izrhv lfi hdliwh ztzrmhg gsvn? Li szev dv ozrw gsrh yfiwvm lm lgsvih? Lm hl-xzoovw drgxsvih? Hgizb xsrowivm gzftsg gsv dzbh lu ulfo hlixvib, gsvri ylwrvh nfgzgvw gsilfts yozhksvnlfh irgfzo. Hvmg gl urtsg nlmhgvih gslfts gsvb xlfow mlg wrhgrmtfrhs tllw uiln vero. Gsv uorxpvi lu sfnzmrgb olmt vcgrmtfrhsvw drgsrm gsvn. Bvh, gsvri mfnyvih szev wdrmwovw gsilfts gsv bvzih. Yfg z uvd hgroo ilzn lfi ozmwh, luuvirmt gsvri yollwb dlip uli xlrm. Gl gsrh wzb gsvb hsznv fh drgs gsvri evib vcrhgvmxv! Gsv Mligs yovvwh, uolttvw yb dzi. Gsv yzggovh ziv gsv tlwh' dsrk, xszhgrhvnvmg uli lfi hrmh! Zmw ovg fh mlg ulitvg gsv gviilih, gsv hxlfitvh uiln yvblmw lfi dliow! Gsv Drow Sfmg irwvh gsv hpb drgs vevib ufoo nllm! Gsv wzip izrwvih zywfxg lfi xsrowivm rmgl ozmwh fmpmldm! Hlnv hzb gsvb svizow z hvxlmw Xlmqfmxgrlm! Xzm dv xszig z xlfihv yzxp rmgl gsv ortsg? Droo dv urmw gsv hgivmtgs gl yzmrhs gsv nztvh uiln lfi prmtwlnh? Fmrgv zilfmw gsv dzings lu gsv Vgvimzo Uriv? Mrts rh gsv Grnv lu gsv Hdliw zmw gsv Zcv! Mlmv droo urtsg gsrh dzi rm lfi hgvzw! Mrts rh gsv Grnv lu Nzwmvhh zmw Wrhwzrm!"
```

**Expected:**
My atbash decoder should pick it up and decode it.

**Versions:**
 - Windows 10 1909
 - Python version: 3.7.4
 - Ciphey versions: 5.0.0

**Comment by bee-san** [comment]
that's a Autumn checker problem and as the name implies it is also my problem 😅😂 sorry!
