### ISSUE TITLE
how to solve this pronlem

### ISSUE THREAD

**Issue by PureWaterSun** [Ciphey/Ciphey#322]
192:~ hh$ ciphey 
Traceback (most recent call last):
  File "/usr/local/bin/ciphey", line 5, in <module>
    from ciphey.ciphey import main
  File "/usr/local/lib/python3.7/site-packages/ciphey/__init__.py", line 1, in <module>
    from . import common
  File "/usr/local/lib/python3.7/site-packages/ciphey/common.py", line 5, in <module>
    import cipheycore
  File "/usr/local/lib/python3.7/site-packages/cipheycore/__init__.py", line 13, in <module>
    from . import _ciphey_core_py
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/cipheycore/_ciphey_core_py.so, 2): Library not loaded: /usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/Python
  Referenced from: /usr/local/lib/python3.7/site-packages/cipheycore/_ciphey_core_py.so
  Reason: image not found

**Comment by brandonskerritt** [comment]
Hey!

You did not fill out the bug template, so we cannot help you. Please fill it out :)
