### ISSUE TITLE
python3.8 compatibility?

### ISSUE THREAD

**Issue by baptistapedro** [Ciphey/Ciphey#398]
```
nasa@ubuntu:~$ sudo docker run  remnux/ciphey -t "++UIVczSLksSfPnrax4tTA=="
Traceback (most recent call last):
  File "/usr/local/bin/ciphey", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ciphey/ciphey.py", line 234, in main
    config.complete_config()
  File "/usr/local/lib/python3.8/site-packages/ciphey/iface/_config.py", line 198, in complete_config
    self.load_objs()
  File "/usr/local/lib/python3.8/site-packages/ciphey/iface/_config.py", line 143, in load_objs
    self.objs["checker"] = self(_fwd.registry.get_named(self.checker, Checker))
  File "/usr/local/lib/python3.8/site-packages/ciphey/iface/_config.py", line 113, in __call__
    return self.instantiate(t)
  File "/usr/local/lib/python3.8/site-packages/ciphey/iface/_config.py", line 108, in instantiate
    ret = t(self)
  File "/usr/local/lib/python3.8/site-packages/ciphey/basemods/Checkers/ezcheck.py", line 44, in __init__
    self.checkers.append(config(Brandon))
  File "/usr/local/lib/python3.8/site-packages/ciphey/iface/_config.py", line 113, in __call__
    return self.instantiate(t)
  File "/usr/local/lib/python3.8/site-packages/ciphey/iface/_config.py", line 108, in instantiate
    ret = t(self)
  File "/usr/local/lib/python3.8/site-packages/ciphey/basemods/Checkers/brandon.py", line 188, in __init__
    self.top1000Words = config.get_resource(self._params().get("top1000"))
  File "/usr/local/lib/python3.8/site-packages/ciphey/iface/_config.py", line 208, in get_resource
    return self(_fwd.registry.get_named(loader, ResourceLoader))(name)
  File "/usr/local/lib/python3.8/site-packages/ciphey/iface/_modules.py", line 235, in __call__
    return self.getResource(*args)
  File "/usr/local/lib/python3.8/site-packages/ciphey/basemods/Resources/cipheydists.py", line 32, in getResource
    return self._getters[prefix](name)
  File "/usr/local/lib/python3.8/site-packages/cipheydists/__init__.py", line 19, in get_list
    return json.loads(pkgutil.get_data(__name__, os.path.join("list", name) + ".json"))
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by bee-san** [comment]
no template so closing.
