### ISSUE TITLE
Trying to run in docker fails, possibly an issue with python3.8

### ISSUE THREAD

**Issue by mitchharvey** [Ciphey/Ciphey#413]
**⚠️IMPORTANT⚠️ if you do not fill this out, we will automatically delete your issue. We will not help anyone that cannot fill out this template.**

- [x] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)

yes

**Describe the bug**
Not working with docker. Running the exact command referenced in the documentation:
`docker run -it --rm remnux/ciphey "=MXazlHbh5WQgUmchdHbh1EIy9mZgQXarx2bvRFI4VnbpxEIBBiO4VnbNVkU"`
Returns:
```
Traceback (most recent call last):
  File "/usr/local/bin/ciphey", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ciphey/ciphey.py", line 221, in main
    config.complete_config()
  File "/usr/local/lib/python3.8/site-packages/ciphey/iface/_config.py", line 196, in complete_config
    self.load_objs()
  File "/usr/local/lib/python3.8/site-packages/ciphey/iface/_config.py", line 141, in load_objs
    self.objs["checker"] = self(_fwd.registry.get_named(self.checker, PolymorphicChecker))
  File "/usr/local/lib/python3.8/site-packages/ciphey/iface/_config.py", line 112, in __call__
    return self.instantiate(t)
  File "/usr/local/lib/python3.8/site-packages/ciphey/iface/_config.py", line 107, in instantiate
    ret = t(self)
  File "/usr/local/lib/python3.8/site-packages/ciphey/iface/_modules.py", line 163, in __init__
    self._base = cls(config)
  File "/usr/local/lib/python3.8/site-packages/ciphey/basemods/Checkers/ezcheck.py", line 50, in __init__
    self.checkers.append(config(Brandon))
  File "/usr/local/lib/python3.8/site-packages/ciphey/iface/_config.py", line 112, in __call__
    return self.instantiate(t)
  File "/usr/local/lib/python3.8/site-packages/ciphey/iface/_config.py", line 107, in instantiate
    ret = t(self)
  File "/usr/local/lib/python3.8/site-packages/ciphey/iface/_modules.py", line 163, in __init__
    self._base = cls(config)
  File "/usr/local/lib/python3.8/site-packages/ciphey/basemods/Checkers/brandon.py", line 191, in __init__
    self.top1000Words = config.get_resource(self._params().get("top1000"))
  File "/usr/local/lib/python3.8/site-packages/ciphey/iface/_config.py", line 206, in get_resource
    return self(_fwd.registry.get_named(loader, ResourceLoader))(name)
  File "/usr/local/lib/python3.8/site-packages/ciphey/iface/_modules.py", line 282, in __call__
    return self.getResource(*args)
  File "/usr/local/lib/python3.8/site-packages/ciphey/basemods/Resources/cipheydists.py", line 32, in getResource
    return self._getters[prefix](name)
  File "/usr/local/lib/python3.8/site-packages/cipheydists/__init__.py", line 19, in get_list
    return json.loads(pkgutil.get_data(__name__, os.path.join("list", name) + ".json"))
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Plaintext**
**⚠️IMPORTANT⚠️ The below code is non-negotiable for "Ciphey didn't decrypt...." problems. If you do not tell us your plaintext, we will not help you.**

```
Not sure what the plaintext is, it was the example from the documentation
```
**Version**
**⚠️IMPORTANT⚠️ We need this information because different environments will induce different bugs in Ciphey**
 - OS/Distro: macOS Catalina
 - Python version: 3.8
 - Ciphey versions: Whatever version is in docker right now
 - Did you use Docker? Yes

**Verbose Output**
**⚠️IMPORTANT⚠️ Verbose output will tell us why it's not working the way we expected it to be.**
https://pastebin.com/TMVDnk4f

**To Reproduce**
1. What input did you use? `docker run -it --rm remnux/ciphey "=MXazlHbh5WQgUmchdHbh1EIy9mZgQXarx2bvRFI4VnbpxEIBBiO4VnbNVkU"`
2. What flags / arguments did you use? No extra flags or arguments

**Expected behavior**
To see ciphey decrypt or at least attempt to decrypt the input

**Any other information?**
Related to #398. But I actually filled out the template.

**Comment by mitchharvey** [comment]
I found a workaround by using a different docker base image `python:3.7.9-slim-buster`

So the full dockerfile just looks like:
```
FROM python:3.7.9-slim-buster
LABEL version="1.1"
LABEL description="Ciphey - An Automated Decoding and Decryption Tool"
LABEL maintainer="Lenny Zeltser"
ENV LANG C.UTF-8
ENV LANGUAGE C.UTF-8
ENV LC_ALL C.UTF-8

USER root

RUN pip3 install --upgrade pip && \
  pip3 install --upgrade ciphey && \
  groupadd -r nonroot && \
  useradd -m -r -g nonroot -d /home/nonroot -s /usr/sbin/nologin -c "Nonroot User" nonroot && \
  mkdir -p /home/nonroot/workdir && \
  chown -R nonroot:nonroot /home/nonroot

USER nonroot
ENV HOME /home/nonroot
WORKDIR /home/nonroot/workdir
VOLUME ["/home/nonroot/workdir"]
ENV USER nonroot
ENTRYPOINT ["/usr/local/bin/ciphey"]
CMD ["--help"]
```

This doesn't fix the issue, since ciphey should be able to work with python3.8, but this is a possible temporary workaround

**Comment by CMNatic** [comment]
Hi! 

I'm only just being drafted in to have a look at this. Thanks for raising the issue, I understand what the problem is here. As it stands, Ciphey relies on REMnux's DockerHub Repo. We can't do any CI/testing and issues such as caching (which is where I think this problem specifically lays within)

I'm going to be making Ciphey a little bit more self-sustainable in this regard over the next day or so. 

> This doesn't fix the issue, since Ciphey should be able to work with python3.8, but this is a possible temporary workaround

Exactly this for the time being! (:

I've pushed a working build to `cmnatic/ciphey` in lieu of creating a Ciphey organisation tomorrow, in the mean while, you can see example usage below:

`docker run -it --rm cmnatic/ciphey =MXazlHbh5WQgUmchdHbh1EIy9mZgQXarx2bvRFI4VnbpxEIBBiO4VnbNVkU`

### Result on a brand new DO Droplet:
> replace "=MXazlHbh5WQgUmchdHbh1EIy9mZgQXarx2bvRFI4VnbpxEIBBiO4VnbNVkU" with your value appropriately

![image](https://user-images.githubusercontent.com/4163116/93396898-6273c000-f870-11ea-8525-6107aa1e2d49.png)


### As it stands, files cannot be parsed to Ciphey i.e. `ciphey -f input.txt` as I wasn't *quite* expecting to be anywhere near publishing yet.

The[ Dockerfile](https://github.com/CMNatic/Ciphey/blob/cmn-dockerfile-py-deb10/Dockerfile) that this is created from is a "band-aid" until I can afford the time to implement all of the above ^^ (note how there are minuscule changes made from the REMnux Dockerfile, where it's accredited nonetheless)
