### ISSUE TITLE
Exception when trying Baudot cipher

### ISSUE THREAD

**Issue by pkubiak** [Ciphey/Ciphey#530]
- [x] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)

**Describe the bug**
When ciphey is run as follow:
```bash
ciphey -t "11111 01001 00011 01110 10011 10100 00000 11011"
```
during the search the exception is thrown:
```
Traceback (most recent call last):
  File "/home/.../.local/bin/ciphey", line 8, in <module>
    sys.exit(main())
  File "/home/.../.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/.../.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/.../.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/.../.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/.../.local/lib/python3.8/site-packages/ciphey/ciphey.py", line 262, in main
    result = decrypt(config, kwargs["text"])
  File "/home/.../.local/lib/python3.8/site-packages/ciphey/ciphey.py", line 40, in decrypt
    res: Optional[iface.SearchResult] = config.objs["searcher"].search(ctext)
  File "/home/.../.local/lib/python3.8/site-packages/ciphey/basemods/Searchers/ausearch.py", line 249, in search
    self.recursive_expand(root, False)
  File "/home/.../.local/lib/python3.8/site-packages/ciphey/basemods/Searchers/ausearch.py", line 228, in recursive_expand
    self.expand_decodings(node)
  File "/home/.../.local/lib/python3.8/site-packages/ciphey/basemods/Searchers/ausearch.py", line 220, in expand_decodings
    self.recursive_expand(new_node, False)
  File "/home/.../.local/lib/python3.8/site-packages/ciphey/basemods/Searchers/ausearch.py", line 228, in recursive_expand
    self.expand_decodings(node)
  File "/home/.../.local/lib/python3.8/site-packages/ciphey/basemods/Searchers/ausearch.py", line 209, in expand_decodings
    res = inst(val)
  File "/home/.../.local/lib/python3.8/site-packages/ciphey/iface/_modules.py", line 196, in __call__
    return self.decode(*args)
  File "/home/.../.local/lib/python3.8/site-packages/ciphey/basemods/Decoders/baudot.py", line 19, in decode
    ret += self.BAUDOT_DICT["+" + i]
```

**Version**
 - OS/Distro: Arch
 - Python version: 3.8.6
 - Ciphey versions: ciphey: 5.10.0, cipheycore: 0.3.2, cipheydists: 0.3.33
 - Did you use Docker? no

**Verbose Output**
https://gist.github.com/pkubiak/aa6f020d5cab3964ef098727a263b0e8

**Expected behavior**
Exception is not thrown

**Comment by Itamikame** [comment]
Hello pkubiak,

i am the one who implemented the baudot decoder.
I didn't include a mapping for "00000" because that would translate into null and i thought that would not be necessary but will add it to the mapping as an empty character so that no error happens.

Kind Regards

Itamikame

**Comment by pkubiak** [comment]
Hi @Itamikame, thanks for your reply.
Sure, If 00000 is a legal code then it is good idea to support it, but I think that If a message can not be decoded using baudot then no exception should be raised. The message could still have been encoded using a different cipher even if it looks like a Baudot. Especially message such as:
```
00000 00001 00010 00011 00100 00101 00110 00111 01000 01001 01010 01011 01100 01101 01110 01111 10000 10001 10010 10011 10100 10101 10110 10111 11000 11001 11010 11011 11100 11101 11110 11111
```
Should not generate any exceptions. So I think that little changes in decoding algorithm may be needed.
