### ISSUE TITLE
Ciphey TypeError with Python 3.9

### ISSUE THREAD

**Issue by DCsunset** [Ciphey/Ciphey#558]
**⚠️IMPORTANT⚠️ if you do not fill this out, we will automatically delete your issue. We will not help anyone that cannot fill out this template.**

- [x] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)

**Describe the bug**
After installing Ciphey using pip3, running Ciphey with any argument will cause the problem.

**Plaintext**
**⚠️IMPORTANT⚠️ The below code is non-negotiable for "Ciphey didn't decrypt...." problems. If you do not tell us your plaintext, we will not help you.** 

```
raceback (most recent call last):
  File "<home>/.local/bin/ciphey", line 5, in <module>
    from ciphey.ciphey import main
  File "<home>/.local/lib/python3.9/site-packages/ciphey/__init__.py", line 1, in <module>
    from . import basemods, common, iface
  File "<home>/.local/lib/python3.9/site-packages/ciphey/basemods/__init__.py", line 1, in <module>
    from . import Checkers, Crackers, Decoders, Resources, Searchers
  File "<home>/.local/lib/python3.9/site-packages/ciphey/basemods/Checkers/__init__.py", line 1, in <module>
    from . import any, brandon, ezcheck, format, human, quorum, regex
  File "<home>/.local/lib/python3.9/site-packages/ciphey/basemods/Checkers/any.py", line 3, in <module>
    from ciphey.iface import Config, ParamSpec, PolymorphicChecker, registry
  File "<home>/.local/lib/python3.9/site-packages/ciphey/iface/__init__.py", line 1, in <module>
    from ._config import Config
  File "<home>/.local/lib/python3.9/site-packages/ciphey/iface/_config.py", line 11, in <module>
    from ._modules import PolymorphicChecker, ResourceLoader, Searcher
  File "<home>/.local/lib/python3.9/site-packages/ciphey/iface/_modules.py", line 208, in <module>
    class CrackResult(NamedTuple, Generic[T]):
  File "/usr/lib/python3.9/typing.py", line 1820, in _namedtuple_mro_entries
    raise TypeError("Multiple inheritance with NamedTuple is not supported")
TypeError: Multiple inheritance with NamedTuple is not supported
```
**Version**
**⚠️IMPORTANT⚠️ We need this information because different environments will induce different bugs in Ciphey**
 - OS/Distro: Arch Linux
 - Python version: Python 3.9.0
 - Ciphey versions: ciphey 5.11.0, cipheycore 0.3.2, cipherdists 0.3.34
 - Did you use Docker? No

**Verbose Output**
**⚠️IMPORTANT⚠️ Verbose output will tell us why it's not working the way we expected it to be.**
Run Ciphey with `ciphey -vvv` and paste the results into [Pastebin.com](https://pastebin.com) or a [GitHub Gist](https://gist.github.com/)

Verbose output is the same as the plaintext.

**To Reproduce**
1. What input did you use? Any input or without input.
2. What flags / arguments did you use? Any argument or without argument

**Expected behavior**
Ciphey runs without this error.

**Any other information?**

**Comment by SkeletalDemise** [comment]
You say you are using Ciphey `5.11.0`. That release is broken and was pulled from PyPI. You need to downgrade to Ciphey version `5.10.0`. Try seeing if that fixes the error.

**Comment by DCsunset** [comment]
Thank you for your reply.

I have downgraded Ciphey to `5.10.0`, but the same error still occurs, with some slight changes:

```
Traceback (most recent call last):
  File "<home>/.local/bin/ciphey", line 5, in <module>
    from ciphey.ciphey import main
  File "<home>/.local/lib/python3.9/site-packages/ciphey/__init__.py", line 3, in <module>
    from . import iface
  File "<home>/.local/lib/python3.9/site-packages/ciphey/iface/__init__.py", line 1, in <module>
    from ._config import Config
  File "<home>/.local/lib/python3.9/site-packages/ciphey/iface/_config.py", line 21, in <module>
    from ._modules import Checker, Searcher, ResourceLoader, PolymorphicChecker
  File "<home>/.local/lib/python3.9/site-packages/ciphey/iface/_modules.py", line 225, in <module>
    class CrackResult(NamedTuple, Generic[T]):
  File "/usr/lib/python3.9/typing.py", line 1820, in _namedtuple_mro_entries
    raise TypeError("Multiple inheritance with NamedTuple is not supported")
TypeError: Multiple inheritance with NamedTuple is not supported
```

The versions of related packages:

* ciphey: 5.10.0
* cipheycore: 0.3.2
* cipheydists: 0.3.34

**Comment by SkeletalDemise** [comment]
Hello, although Python 3.9 on Linux should work for CipheyCore, can you try using Python 3.8 or 3.7 instead of Python 3.9? Someone else had this error before and using Python 3.7 or 3.8 worked.

**Comment by DCsunset** [comment]
I have tried Python 3.8 and this error doesn't occur anymore. It seems a specific error using Python 3.9.

**Comment by cocoonkid** [comment]
3.8.6 here. Same error

**Comment by adigeefe** [comment]
>Worked for me 
```bash
python3.8 -m pip install ciphey --upgrade
```

**Comment by eggman64** [comment]
This is caused by to https://github.com/python/cpython/pull/19363

**Comment by scott-m-willett** [comment]
Workaround for now may be to comment out line 1880 and 1881 from the file /usr/lib/python3.9/typing.py or the equivalent in your case (line 1820 in your case). Worked for me. Could be other consequences out of this in the future.

This may help you find the lines

def _namedtuple_mro_entries(bases):
    # if len(bases) > 1:
        # raise TypeError("Multiple inheritance with NamedTuple is not supported")
