### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 695: illegal multibyte sequence

### ISSUE THREAD

**Issue by cuizhijun** [Ciphey/Ciphey#668]
C:\Users\xxx>ciphey -t "aGVsbG8gbXkgbmFtZSBpcyBiZWU="
Traceback (most recent call last):
  File "d:\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python\Python37\Scripts\ciphey.exe\__main__.py", line 7, in <module>
  File "d:\python\python37\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "d:\python\python37\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "d:\python\python37\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\python\python37\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\python\python37\lib\site-packages\ciphey\ciphey.py", line 222, in main
    config.complete_config()
  File "d:\python\python37\lib\site-packages\ciphey\iface\_config.py", line 189, in complete_config
    self.load_objs()
  File "d:\python\python37\lib\site-packages\ciphey\iface\_config.py", line 132, in load_objs
    _fwd.registry.get_named(self.checker, PolymorphicChecker)
  File "d:\python\python37\lib\site-packages\ciphey\iface\_config.py", line 102, in __call__
    return self.instantiate(t)
  File "d:\python\python37\lib\site-packages\ciphey\iface\_config.py", line 97, in instantiate
    ret = t(self)
  File "d:\python\python37\lib\site-packages\ciphey\iface\_modules.py", line 153, in __init__
    self._base = cls(config)
  File "d:\python\python37\lib\site-packages\ciphey\basemods\Checkers\ezcheck.py", line 46, in __init__
    self.checkers.append(config(What))
  File "d:\python\python37\lib\site-packages\ciphey\iface\_config.py", line 102, in __call__
    return self.instantiate(t)
  File "d:\python\python37\lib\site-packages\ciphey\iface\_config.py", line 97, in instantiate
    ret = t(self)
  File "d:\python\python37\lib\site-packages\ciphey\iface\_modules.py", line 153, in __init__
    self._base = cls(config)
  File "d:\python\python37\lib\site-packages\ciphey\basemods\Checkers\what.py", line 59, in __init__
    self.id = identifier.Identifier()
  File "d:\python\python37\lib\site-packages\pywhat\identifier.py", line 10, in __init__
    self.regex_id = RegexIdentifier()
  File "d:\python\python37\lib\site-packages\pywhat\regex_identifier.py", line 11, in __init__
    self.regexes = json.load(myfile)
  File "d:\python\python37\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 695: illegal multibyte sequence

**Comment by bee-san** [comment]
Moved issue to correct project https://github.com/bee-san/pyWhat/issues/116
