### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 695: illegal multibyte sequence

### ISSUE THREAD

**Issue by zerorzeror** [Ciphey/Ciphey#675]
OS is Windows10, Chinese.

(Ciphey) D:\Virtualenvs>ciphey "amFjayBjdWk="

Error Tip:

Traceback (most recent call last):
  File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Virtualenvs\Ciphey\Scripts\ciphey.exe\__main__.py", line 7, in <module>
  File "d:\virtualenvs\ciphey\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "d:\virtualenvs\ciphey\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "d:\virtualenvs\ciphey\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\virtualenvs\ciphey\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\virtualenvs\ciphey\lib\site-packages\ciphey\ciphey.py", line 222, in main
    config.complete_config()
  File "d:\virtualenvs\ciphey\lib\site-packages\ciphey\iface\_config.py", line 189, in complete_config
    self.load_objs()
  File "d:\virtualenvs\ciphey\lib\site-packages\ciphey\iface\_config.py", line 132, in load_objs
    _fwd.registry.get_named(self.checker, PolymorphicChecker)
  File "d:\virtualenvs\ciphey\lib\site-packages\ciphey\iface\_config.py", line 102, in __call__
    return self.instantiate(t)
  File "d:\virtualenvs\ciphey\lib\site-packages\ciphey\iface\_config.py", line 97, in instantiate
    ret = t(self)
  File "d:\virtualenvs\ciphey\lib\site-packages\ciphey\iface\_modules.py", line 153, in __init__
    self._base = cls(config)
  File "d:\virtualenvs\ciphey\lib\site-packages\ciphey\basemods\Checkers\ezcheck.py", line 46, in __init__
    self.checkers.append(config(What))
  File "d:\virtualenvs\ciphey\lib\site-packages\ciphey\iface\_config.py", line 102, in __call__
    return self.instantiate(t)
  File "d:\virtualenvs\ciphey\lib\site-packages\ciphey\iface\_config.py", line 97, in instantiate
    ret = t(self)
  File "d:\virtualenvs\ciphey\lib\site-packages\ciphey\iface\_modules.py", line 153, in __init__
    self._base = cls(config)
  File "d:\virtualenvs\ciphey\lib\site-packages\ciphey\basemods\Checkers\what.py", line 59, in __init__
    self.id = identifier.Identifier()
  File "d:\virtualenvs\ciphey\lib\site-packages\pywhat\identifier.py", line 10, in __init__
    self.regex_id = RegexIdentifier()
  File "d:\virtualenvs\ciphey\lib\site-packages\pywhat\regex_identifier.py", line 11, in __init__
    self.regexes = json.load(myfile)
  File "C:\Python37\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 695: illegal multibyte sequence

**Comment by amadejpapez** [comment]
Hi! This is a known issue [#116](https://github.com/bee-san/pyWhat/issues/116) and there is already a potential fix in [#122](https://github.com/bee-san/pyWhat/pull/122) :)

**Comment by oneout187** [comment]
How do i fix this

**Comment by zerorzeror** [comment]
I fixed tihs,thank you.
find ..\Lib\site-packages\pywhat\magic_numbers.py

Revise  "with open(fullpath, "r", encoding="utf8", errors="ignore") as myfile:" To “with open(fullpath, "rb") as myfile:”

“with open(file_loc, "r", encoding="utf8", errors="ignore") as myfile:” To “with open(file_loc, "r", encoding="utf-8", errors="ignore") as myfile:”

**Comment by qtccz** [comment]
I tried to fix it in ..\Lib\site-packages\pywhat\regex_identifier.py
Line 10 changes "with open(fullpath, "r") as myfile" to "with open(fullpath, "rb") as myfile"，Got resolved

**Comment by amadejpapez** [comment]
> I tried to fix it in ..\Lib\site-packages\pywhat\regex_identifier.py
> 
> Line 10 changes "with open(fullpath, "r") as myfile" to "with open(fullpath, "rb") as myfile"，Got resolved

Hi! Which version of pyWhat are you using and can you try it with the latest release?

**Comment by SkeletalDemise** [comment]
This was fixed in pyWhat in this PR: https://github.com/bee-san/pyWhat/pull/122. Run `pip install pywhat --upgrade` and it should work. 👍

**Comment by IIIIIan** [comment]
> This was fixed in pyWhat in this PR: [bee-san/pyWhat#122](https://github.com/bee-san/pyWhat/pull/122). Run `pip install pywhat --upgrade` and it should work. 👍

thx, it works
