### ISSUE TITLE
Brainfuck error

### ISSUE THREAD

**Issue by kerszl** [Ciphey/Ciphey#684]
ciphey -t '++++++++++[>+>+++>+++++++>++++++++++<<<<-]>>>------------------....'

Traceback (most recent call last):
File "/usr/local/bin/ciphey", line 8, in
sys.exit(main())
File "/usr/lib/python3/dist-packages/click/core.py", line 829, in call
return self.main(*args, **kwargs)
File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/ciphey/ciphey.py", line 263, in main
result = decrypt(config, kwargs["text"])
File "/usr/local/lib/python3.9/dist-packages/ciphey/ciphey.py", line 32, in decrypt
res: Optional[iface.SearchResult] = config.objs["searcher"].search(ctext)
File "/usr/local/lib/python3.9/dist-packages/ciphey/basemods/Searchers/ausearch.py", line 281, in search
self.recursive_expand(node)
File "/usr/local/lib/python3.9/dist-packages/ciphey/basemods/Searchers/ausearch.py", line 221, in recursive_expand
self.expand_decodings(node)

**Comment by SkeletalDemise** [comment]
This isn't really a bug. Your code `++++++++++[>+>+++>+++++++>++++++++++<<<<-]>>>------------------....` decodes to  `4444` which isn't English or anything that Ciphey's checkers would catch. This is how Ciphey checks if something is successfully decoded/decrypted or not: https://github.com/Ciphey/Ciphey/wiki/Checkers,-explained
If it's not English, JSON, or anything in [pyWhat](https://github.com/bee-san/pyWhat) (URLs, API keys, email addresses, phone numbers, etc.) then Ciphey won't catch it.

If you want to test Ciphey run this: `ciphey -t "++++++++++[>+>+++>+++++++>++++++++++<<<<-]>>>++++++++++++++.>++++.+.++++++++++.<<++.>>----------.++++++++++.<<.>+++++++++++++.<.>>+.<++++.>-.+."`
