### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by FalcoGer** [Ciphey/Ciphey#741]
- [X] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)

**Describe the bug**
Unable to install with python3.10 and python3.9

**Plaintext**

```
N/A
```
**Version**
 - OS/Distro: Ubuntu Mate 22.04
 - Python version: Python 3.9.13 / Python 3.10.4
 - Ciphey versions:
 ```text
WARNING: Package(s) not found: ciphey
Name: cipheycore
Version: 0.3.2
Summary:
Home-page:
Author: Cyclic3
Author-email: cyclic3.git@gmail.com
License:
Location: /home/paul/repositories/hacking/ciphey/lib/python3.9/site-packages
Requires:
Required-by:
---
Name: cipheydists
Version: 0.3.35
Summary: A collection of distributions, character sets and dictionaries for use in ciphey
Home-page:
Author: Cyclic3
Author-email: cyclic3.git@gmail.com
License:
Location: /home/paul/repositories/hacking/ciphey/lib/python3.9/site-packages
Requires:
Required-by:
```
 - Did you use Docker?: NO

**Verbose Output**

Python 3.9.13 compiled from source just for ciphey
```text
pip install ciphey --upgrade
Collecting ciphey
  Using cached ciphey-5.14.0-py3-none-any.whl (90 kB)
Requirement already satisfied: appdirs<2.0.0,>=1.4.4 in ./lib/python3.9/site-packages (from ciphey) (1.4.4)
Requirement already satisfied: base91<2.0.0,>=1.0.1 in ./lib/python3.9/site-packages (from ciphey) (1.0.1)
Requirement already satisfied: click<9.0.0,>=7.1.2 in ./lib/python3.9/site-packages (from ciphey) (7.1.2)
Requirement already satisfied: rich<11,>=4 in ./lib/python3.9/site-packages (from ciphey) (10.16.2)
Requirement already satisfied: base58<3.0.0,>=2.0.1 in ./lib/python3.9/site-packages (from ciphey) (2.1.1)
Collecting pylint<3.0.0,>=2.6.0
  Using cached pylint-2.14.1-py3-none-any.whl (486 kB)
Requirement already satisfied: pyyaml<6.0.0,>=5.3.1 in ./lib/python3.9/site-packages (from ciphey) (5.4.1)
Collecting flake8<4.0.0,>=3.8.4
  Using cached flake8-3.9.2-py2.py3-none-any.whl (73 kB)
Requirement already satisfied: pybase62<0.5.0,>=0.4.3 in ./lib/python3.9/site-packages (from ciphey) (0.4.3)
Requirement already satisfied: mock<5.0.0,>=4.0.3 in ./lib/python3.9/site-packages (from ciphey) (4.0.3)
Requirement already satisfied: cipheydists<0.4.0,>=0.3.34 in ./lib/python3.9/site-packages (from ciphey) (0.3.35)
Requirement already satisfied: cipheycore<0.4.0,>=0.3.2 in ./lib/python3.9/site-packages (from ciphey) (0.3.2)
Collecting pywhat<1.2.0,>=0.2.5
  Using cached pywhat-1.1.0-py3-none-any.whl (32 kB)
Requirement already satisfied: loguru<0.6.0,>=0.5.3 in ./lib/python3.9/site-packages (from ciphey) (0.5.3)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in ./lib/python3.9/site-packages (from flake8<4.0.0,>=3.8.4->ciphey) (0.6.1)
Requirement already satisfied: pyflakes<2.4.0,>=2.3.0 in ./lib/python3.9/site-packages (from flake8<4.0.0,>=3.8.4->ciphey) (2.3.1)
Requirement already satisfied: pycodestyle<2.8.0,>=2.7.0 in ./lib/python3.9/site-packages (from flake8<4.0.0,>=3.8.4->ciphey) (2.7.0)
Requirement already satisfied: platformdirs>=2.2.0 in ./lib/python3.9/site-packages (from pylint<3.0.0,>=2.6.0->ciphey) (2.5.2)
Requirement already satisfied: typing-extensions>=3.10.0 in ./lib/python3.9/site-packages (from pylint<3.0.0,>=2.6.0->ciphey) (4.2.0)
Requirement already satisfied: tomli>=1.1.0 in ./lib/python3.9/site-packages (from pylint<3.0.0,>=2.6.0->ciphey) (2.0.1)
Requirement already satisfied: dill>=0.2 in ./lib/python3.9/site-packages (from pylint<3.0.0,>=2.6.0->ciphey) (0.3.5.1)
Requirement already satisfied: isort<6,>=4.2.5 in ./lib/python3.9/site-packages (from pylint<3.0.0,>=2.6.0->ciphey) (5.10.1)
Requirement already satisfied: tomlkit>=0.10.1 in ./lib/python3.9/site-packages (from pylint<3.0.0,>=2.6.0->ciphey) (0.11.0)
Collecting astroid<=2.12.0-dev0,>=2.11.5
  Using cached astroid-2.11.5-py3-none-any.whl (250 kB)
Collecting langdetect<2.0.0,>=1.0.8
  Using cached langdetect-1.0.9.tar.gz (981 kB)
  Preparing metadata (setup.py) ... done
Collecting name_that_hash<2.0.0,>=1.7.0
  Using cached name_that_hash-1.10.0-py3-none-any.whl (29 kB)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in ./lib/python3.9/site-packages (from rich<11,>=4->ciphey) (2.12.0)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in ./lib/python3.9/site-packages (from rich<11,>=4->ciphey) (0.9.1)
Requirement already satisfied: colorama<0.5.0,>=0.4.0 in ./lib/python3.9/site-packages (from rich<11,>=4->ciphey) (0.4.4)
Requirement already satisfied: setuptools>=20.0 in ./lib/python3.9/site-packages (from astroid<=2.12.0-dev0,>=2.11.5->pylint<3.0.0,>=2.6.0->ciphey) (59.6.0)
Requirement already satisfied: wrapt<2,>=1.11 in ./lib/python3.9/site-packages (from astroid<=2.12.0-dev0,>=2.11.5->pylint<3.0.0,>=2.6.0->ciphey) (1.14.1)
Requirement already satisfied: lazy-object-proxy>=1.4.0 in ./lib/python3.9/site-packages (from astroid<=2.12.0-dev0,>=2.11.5->pylint<3.0.0,>=2.6.0->ciphey) (1.7.1)
Requirement already satisfied: six in ./lib/python3.9/site-packages (from langdetect<2.0.0,>=1.0.8->pywhat<1.2.0,>=0.2.5->ciphey) (1.16.0)
Building wheels for collected packages: langdetect
  Building wheel for langdetect (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [129 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/langdetect
      copying langdetect/detector_factory.py -> build/lib/langdetect
      copying langdetect/language.py -> build/lib/langdetect
      copying langdetect/lang_detect_exception.py -> build/lib/langdetect
      copying langdetect/__init__.py -> build/lib/langdetect
      copying langdetect/detector.py -> build/lib/langdetect
      creating build/lib/langdetect/utils
      copying langdetect/utils/unicode_block.py -> build/lib/langdetect/utils
      copying langdetect/utils/messages.py -> build/lib/langdetect/utils
      copying langdetect/utils/__init__.py -> build/lib/langdetect/utils
      copying langdetect/utils/lang_profile.py -> build/lib/langdetect/utils
      copying langdetect/utils/ngram.py -> build/lib/langdetect/utils
      creating build/lib/langdetect/tests
      copying langdetect/tests/test_language.py -> build/lib/langdetect/tests
      copying langdetect/tests/__init__.py -> build/lib/langdetect/tests
      copying langdetect/tests/test_detector.py -> build/lib/langdetect/tests
      running egg_info
      writing langdetect.egg-info/PKG-INFO
      writing dependency_links to langdetect.egg-info/dependency_links.txt
      writing requirements to langdetect.egg-info/requires.txt
      writing top-level names to langdetect.egg-info/top_level.txt
      reading manifest file 'langdetect.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      adding license file 'NOTICE'
      writing manifest file 'langdetect.egg-info/SOURCES.txt'
      creating build/lib/langdetect/profiles
      copying langdetect/profiles/af -> build/lib/langdetect/profiles
      copying langdetect/profiles/ar -> build/lib/langdetect/profiles
      copying langdetect/profiles/bg -> build/lib/langdetect/profiles
      copying langdetect/profiles/bn -> build/lib/langdetect/profiles
      copying langdetect/profiles/ca -> build/lib/langdetect/profiles
      copying langdetect/profiles/cs -> build/lib/langdetect/profiles
      copying langdetect/profiles/cy -> build/lib/langdetect/profiles
      copying langdetect/profiles/da -> build/lib/langdetect/profiles
      copying langdetect/profiles/de -> build/lib/langdetect/profiles
      copying langdetect/profiles/el -> build/lib/langdetect/profiles
      copying langdetect/profiles/en -> build/lib/langdetect/profiles
      copying langdetect/profiles/es -> build/lib/langdetect/profiles
      copying langdetect/profiles/et -> build/lib/langdetect/profiles
      copying langdetect/profiles/fa -> build/lib/langdetect/profiles
      copying langdetect/profiles/fi -> build/lib/langdetect/profiles
      copying langdetect/profiles/fr -> build/lib/langdetect/profiles
      copying langdetect/profiles/gu -> build/lib/langdetect/profiles
      copying langdetect/profiles/he -> build/lib/langdetect/profiles
      copying langdetect/profiles/hi -> build/lib/langdetect/profiles
      copying langdetect/profiles/hr -> build/lib/langdetect/profiles
      copying langdetect/profiles/hu -> build/lib/langdetect/profiles
      copying langdetect/profiles/id -> build/lib/langdetect/profiles
      copying langdetect/profiles/it -> build/lib/langdetect/profiles
      copying langdetect/profiles/ja -> build/lib/langdetect/profiles
      copying langdetect/profiles/kn -> build/lib/langdetect/profiles
      copying langdetect/profiles/ko -> build/lib/langdetect/profiles
      copying langdetect/profiles/lt -> build/lib/langdetect/profiles
      copying langdetect/profiles/lv -> build/lib/langdetect/profiles
      copying langdetect/profiles/mk -> build/lib/langdetect/profiles
      copying langdetect/profiles/ml -> build/lib/langdetect/profiles
      copying langdetect/profiles/mr -> build/lib/langdetect/profiles
      copying langdetect/profiles/ne -> build/lib/langdetect/profiles
      copying langdetect/profiles/nl -> build/lib/langdetect/profiles
      copying langdetect/profiles/no -> build/lib/langdetect/profiles
      copying langdetect/profiles/pa -> build/lib/langdetect/profiles
      copying langdetect/profiles/pl -> build/lib/langdetect/profiles
      copying langdetect/profiles/pt -> build/lib/langdetect/profiles
      copying langdetect/profiles/ro -> build/lib/langdetect/profiles
      copying langdetect/profiles/ru -> build/lib/langdetect/profiles
      copying langdetect/profiles/sk -> build/lib/langdetect/profiles
      copying langdetect/profiles/sl -> build/lib/langdetect/profiles
      copying langdetect/profiles/so -> build/lib/langdetect/profiles
      copying langdetect/profiles/sq -> build/lib/langdetect/profiles
      copying langdetect/profiles/sv -> build/lib/langdetect/profiles
      copying langdetect/profiles/sw -> build/lib/langdetect/profiles
      copying langdetect/profiles/ta -> build/lib/langdetect/profiles
      copying langdetect/profiles/te -> build/lib/langdetect/profiles
      copying langdetect/profiles/th -> build/lib/langdetect/profiles
      copying langdetect/profiles/tl -> build/lib/langdetect/profiles
      copying langdetect/profiles/tr -> build/lib/langdetect/profiles
      copying langdetect/profiles/uk -> build/lib/langdetect/profiles
      copying langdetect/profiles/ur -> build/lib/langdetect/profiles
      copying langdetect/profiles/vi -> build/lib/langdetect/profiles
      copying langdetect/profiles/zh-cn -> build/lib/langdetect/profiles
      copying langdetect/profiles/zh-tw -> build/lib/langdetect/profiles
      copying langdetect/utils/messages.properties -> build/lib/langdetect/utils
      /home/paul/repositories/hacking/ciphey/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      installing to build/bdist.linux-x86_64/wheel
      running install
      running install_lib
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-qklg2n_a/langdetect_efcf1e318c5c4e988f0a93689f227a38/setup.py", line 11, in <module>
          setup(
        File "/home/paul/repositories/hacking/ciphey/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.9/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/local/lib/python3.9/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/paul/repositories/hacking/ciphey/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 335, in run
          self.run_command('install')
        File "/usr/local/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/paul/repositories/hacking/ciphey/lib/python3.9/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/usr/local/lib/python3.9/distutils/command/install.py", line 558, in run
          self.run_command(cmd_name)
        File "/usr/local/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.9/distutils/dist.py", line 984, in run_command
          cmd_obj.ensure_finalized()
        File "/usr/local/lib/python3.9/distutils/cmd.py", line 107, in ensure_finalized
          self.finalize_options()
        File "/home/paul/repositories/hacking/ciphey/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 17, in finalize_options
          self.set_undefined_options('install',('install_layout','install_layout'))
        File "/usr/local/lib/python3.9/distutils/cmd.py", line 290, in set_undefined_options
          setattr(self, dst_option, getattr(src_cmd_obj, src_option))
        File "/usr/local/lib/python3.9/distutils/cmd.py", line 103, in __getattr__
          raise AttributeError(attr)
      AttributeError: install_layout
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for langdetect
  Running setup.py clean for langdetect
Failed to build langdetect
Installing collected packages: langdetect, flake8, astroid, pylint, name_that_hash, pywhat, ciphey
  Running setup.py install for langdetect ... error
  error: subprocess-exited-with-error

  × Running setup.py install for langdetect did not run successfully.
  │ exit code: 1
  ╰─> [121 lines of output]
      running install
      /home/paul/repositories/hacking/ciphey/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/langdetect
      copying langdetect/detector_factory.py -> build/lib/langdetect
      copying langdetect/language.py -> build/lib/langdetect
      copying langdetect/lang_detect_exception.py -> build/lib/langdetect
      copying langdetect/__init__.py -> build/lib/langdetect
      copying langdetect/detector.py -> build/lib/langdetect
      creating build/lib/langdetect/utils
      copying langdetect/utils/unicode_block.py -> build/lib/langdetect/utils
      copying langdetect/utils/messages.py -> build/lib/langdetect/utils
      copying langdetect/utils/__init__.py -> build/lib/langdetect/utils
      copying langdetect/utils/lang_profile.py -> build/lib/langdetect/utils
      copying langdetect/utils/ngram.py -> build/lib/langdetect/utils
      creating build/lib/langdetect/tests
      copying langdetect/tests/test_language.py -> build/lib/langdetect/tests
      copying langdetect/tests/__init__.py -> build/lib/langdetect/tests
      copying langdetect/tests/test_detector.py -> build/lib/langdetect/tests
      running egg_info
      writing langdetect.egg-info/PKG-INFO
      writing dependency_links to langdetect.egg-info/dependency_links.txt
      writing requirements to langdetect.egg-info/requires.txt
      writing top-level names to langdetect.egg-info/top_level.txt
      reading manifest file 'langdetect.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      adding license file 'NOTICE'
      writing manifest file 'langdetect.egg-info/SOURCES.txt'
      creating build/lib/langdetect/profiles
      copying langdetect/profiles/af -> build/lib/langdetect/profiles
      copying langdetect/profiles/ar -> build/lib/langdetect/profiles
      copying langdetect/profiles/bg -> build/lib/langdetect/profiles
      copying langdetect/profiles/bn -> build/lib/langdetect/profiles
      copying langdetect/profiles/ca -> build/lib/langdetect/profiles
      copying langdetect/profiles/cs -> build/lib/langdetect/profiles
      copying langdetect/profiles/cy -> build/lib/langdetect/profiles
      copying langdetect/profiles/da -> build/lib/langdetect/profiles
      copying langdetect/profiles/de -> build/lib/langdetect/profiles
      copying langdetect/profiles/el -> build/lib/langdetect/profiles
      copying langdetect/profiles/en -> build/lib/langdetect/profiles
      copying langdetect/profiles/es -> build/lib/langdetect/profiles
      copying langdetect/profiles/et -> build/lib/langdetect/profiles
      copying langdetect/profiles/fa -> build/lib/langdetect/profiles
      copying langdetect/profiles/fi -> build/lib/langdetect/profiles
      copying langdetect/profiles/fr -> build/lib/langdetect/profiles
      copying langdetect/profiles/gu -> build/lib/langdetect/profiles
      copying langdetect/profiles/he -> build/lib/langdetect/profiles
      copying langdetect/profiles/hi -> build/lib/langdetect/profiles
      copying langdetect/profiles/hr -> build/lib/langdetect/profiles
      copying langdetect/profiles/hu -> build/lib/langdetect/profiles
      copying langdetect/profiles/id -> build/lib/langdetect/profiles
      copying langdetect/profiles/it -> build/lib/langdetect/profiles
      copying langdetect/profiles/ja -> build/lib/langdetect/profiles
      copying langdetect/profiles/kn -> build/lib/langdetect/profiles
      copying langdetect/profiles/ko -> build/lib/langdetect/profiles
      copying langdetect/profiles/lt -> build/lib/langdetect/profiles
      copying langdetect/profiles/lv -> build/lib/langdetect/profiles
      copying langdetect/profiles/mk -> build/lib/langdetect/profiles
      copying langdetect/profiles/ml -> build/lib/langdetect/profiles
      copying langdetect/profiles/mr -> build/lib/langdetect/profiles
      copying langdetect/profiles/ne -> build/lib/langdetect/profiles
      copying langdetect/profiles/nl -> build/lib/langdetect/profiles
      copying langdetect/profiles/no -> build/lib/langdetect/profiles
      copying langdetect/profiles/pa -> build/lib/langdetect/profiles
      copying langdetect/profiles/pl -> build/lib/langdetect/profiles
      copying langdetect/profiles/pt -> build/lib/langdetect/profiles
      copying langdetect/profiles/ro -> build/lib/langdetect/profiles
      copying langdetect/profiles/ru -> build/lib/langdetect/profiles
      copying langdetect/profiles/sk -> build/lib/langdetect/profiles
      copying langdetect/profiles/sl -> build/lib/langdetect/profiles
      copying langdetect/profiles/so -> build/lib/langdetect/profiles
      copying langdetect/profiles/sq -> build/lib/langdetect/profiles
      copying langdetect/profiles/sv -> build/lib/langdetect/profiles
      copying langdetect/profiles/sw -> build/lib/langdetect/profiles
      copying langdetect/profiles/ta -> build/lib/langdetect/profiles
      copying langdetect/profiles/te -> build/lib/langdetect/profiles
      copying langdetect/profiles/th -> build/lib/langdetect/profiles
      copying langdetect/profiles/tl -> build/lib/langdetect/profiles
      copying langdetect/profiles/tr -> build/lib/langdetect/profiles
      copying langdetect/profiles/uk -> build/lib/langdetect/profiles
      copying langdetect/profiles/ur -> build/lib/langdetect/profiles
      copying langdetect/profiles/vi -> build/lib/langdetect/profiles
      copying langdetect/profiles/zh-cn -> build/lib/langdetect/profiles
      copying langdetect/profiles/zh-tw -> build/lib/langdetect/profiles
      copying langdetect/utils/messages.properties -> build/lib/langdetect/utils
      running install_lib
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-qklg2n_a/langdetect_efcf1e318c5c4e988f0a93689f227a38/setup.py", line 11, in <module>
          setup(
        File "/home/paul/repositories/hacking/ciphey/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.9/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/local/lib/python3.9/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/paul/repositories/hacking/ciphey/lib/python3.9/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/usr/local/lib/python3.9/distutils/command/install.py", line 558, in run
          self.run_command(cmd_name)
        File "/usr/local/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.9/distutils/dist.py", line 984, in run_command
          cmd_obj.ensure_finalized()
        File "/usr/local/lib/python3.9/distutils/cmd.py", line 107, in ensure_finalized
          self.finalize_options()
        File "/home/paul/repositories/hacking/ciphey/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 17, in finalize_options
          self.set_undefined_options('install',('install_layout','install_layout'))
        File "/usr/local/lib/python3.9/distutils/cmd.py", line 290, in set_undefined_options
          setattr(self, dst_option, getattr(src_cmd_obj, src_option))
        File "/usr/local/lib/python3.9/distutils/cmd.py", line 103, in __getattr__
          raise AttributeError(attr)
      AttributeError: install_layout
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> langdetect

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

Python 3.10.4 (system default)
```text
pip3 install ciphey --upgrade
Collecting ciphey
  Using cached ciphey-5.14.0-py3-none-any.whl (90 kB)
Collecting base91<2.0.0,>=1.0.1
  Using cached base91-1.0.1-py3-none-any.whl (3.4 kB)
Collecting rich<11,>=4
  Using cached rich-10.16.2-py3-none-any.whl (214 kB)
Collecting pyyaml<6.0.0,>=5.3.1
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting flake8<4.0.0,>=3.8.4
  Using cached flake8-3.9.2-py2.py3-none-any.whl (73 kB)
Collecting pylint<3.0.0,>=2.6.0
  Using cached pylint-2.14.1-py3-none-any.whl (486 kB)
Collecting mock<5.0.0,>=4.0.3
  Using cached mock-4.0.3-py3-none-any.whl (28 kB)
Collecting pywhat<1.2.0,>=0.2.5
  Using cached pywhat-1.1.0-py3-none-any.whl (32 kB)
Collecting ciphey
  Using cached ciphey-5.13.0-py3-none-any.whl (90 kB)
Collecting pywhat<0.3.0,>=0.2.5
  Using cached pywhat-0.2.5-py3-none-any.whl (29 kB)
Collecting click-spinner<0.2.0,>=0.1.10
  Using cached click_spinner-0.1.10-py2.py3-none-any.whl (4.0 kB)
Collecting yaspin<1.6,>=0.17
  Using cached yaspin-1.5.0-py2.py3-none-any.whl (27 kB)
Collecting ciphey
  Using cached ciphey-5.12.1-py3-none-any.whl (89 kB)
  Using cached ciphey-5.12.0-py3-none-any.whl (89 kB)
  Using cached ciphey-5.11.3-py3-none-any.whl (88 kB)
  Using cached ciphey-5.11.2-py3-none-any.whl (89 kB)
Collecting click<8.0.0,>=7.1.2
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting ciphey
  Using cached ciphey-5.11.1-py3-none-any.whl (89 kB)
Collecting yaspin<1.5,>=0.17
  Using cached yaspin-1.4.1-py2.py3-none-any.whl (27 kB)
Collecting ciphey
  Using cached ciphey-5.10.0-py3-none-any.whl (87 kB)
Collecting loguru<0.6.0,>=0.5.0
  Using cached loguru-0.5.3-py3-none-any.whl (57 kB)
Collecting yaspin<1.3,>=0.17
  Using cached yaspin-1.2.0-py2.py3-none-any.whl (26 kB)
Collecting ciphey
  Using cached ciphey-5.9.0-py3-none-any.whl (84 kB)
Collecting cipheydists<0.4.0,>=0.3.31
  Using cached cipheydists-0.3.35-py3-none-any.whl (11.6 MB)
Collecting rich<9,>=4
  Using cached rich-8.0.0-py3-none-any.whl (155 kB)
Collecting base58<3.0.0,>=2.0.1
  Using cached base58-2.1.1-py3-none-any.whl (5.6 kB)
Collecting yaspin<1.2,>=0.17
  Using cached yaspin-1.1.0-py2.py3-none-any.whl (26 kB)
Collecting appdirs<2.0.0,>=1.4.4
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting pybase62<0.5.0,>=0.4.3
  Using cached pybase62-0.4.3-py3-none-any.whl (5.0 kB)
Collecting ciphey
  Using cached ciphey-5.8.0-py3-none-any.whl (77 kB)
  Using cached ciphey-5.7.0-py3-none-any.whl (74 kB)
Collecting rich<8,>=4
  Using cached rich-7.1.0-py3-none-any.whl (153 kB)
Collecting yaspin<1.1,>=0.17
  Using cached yaspin-1.0.0-py2.py3-none-any.whl (26 kB)
Collecting ciphey
  Using cached ciphey-5.6.0-py3-none-any.whl (72 kB)
Collecting rich<7,>=4
  Using cached rich-6.2.0-py3-none-any.whl (150 kB)
Collecting ciphey
  Using cached ciphey-5.5.3-py3-none-any.whl (70 kB)
  Using cached ciphey-5.5.2-py3-none-any.whl (69 kB)
  Using cached ciphey-5.4.0-py3-none-any.whl (66 kB)
  Using cached ciphey-5.3.2-py3-none-any.whl (58 kB)
  Using cached ciphey-5.3.1-py3-none-any.whl (58 kB)
  Using cached ciphey-5.3.0-py3-none-any.whl (56 kB)
  Using cached ciphey-5.2.0-py3-none-any.whl (54 kB)
Collecting rich<6,>=4
  Using cached rich-5.2.1-py3-none-any.whl (145 kB)
Collecting ciphey
  Using cached ciphey-5.1.0-py3-none-any.whl (51 kB)
  Using cached ciphey-5.0.0-py3-none-any.whl (50 kB)
Collecting yaspin<0.18.0,>=0.17.0
  Using cached yaspin-0.17.0-py2.py3-none-any.whl (43 kB)
Collecting rich<5.0.0,>=4.0.0
  Using cached rich-4.2.2-py3-none-any.whl (141 kB)
Collecting ciphey
  Using cached ciphey-4.2.1-py3-none-any.whl (38 kB)
Collecting rich<2.0.0,>=1.2.3
  Using cached rich-1.3.1-py3-none-any.whl (126 kB)
Collecting click-option-group<0.6.0,>=0.5.1
  Using cached click_option_group-0.5.3-py3-none-any.whl (11 kB)
Collecting tensorflow<3.0.0,>=2.1.0
  Using cached tensorflow-2.9.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (511.7 MB)
Collecting cipheydists<0.3.0,>=0.2.2
  Using cached cipheydists-0.2.2-py3-none-any.whl (13.0 MB)
Collecting click-completion<0.6.0,>=0.5.2
  Using cached click-completion-0.5.2.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done
Collecting tflite<3.0.0,>=2.2.0
  Using cached tflite-2.4.0-py2.py3-none-any.whl (87 kB)
Collecting ciphey
  Using cached ciphey-4.2.0-py3-none-any.whl (37 kB)
  Using cached Ciphey-3.8.2-py3-none-any.whl (6.2 MB)
Collecting setuptools~=46.1.3
  Using cached setuptools-46.1.3-py3-none-any.whl (582 kB)
Collecting ciphey
  Using cached Ciphey-3.8.1-py3-none-any.whl (6.2 MB)
  Using cached Ciphey-3.8-py3-none-any.whl (6.2 MB)
  Using cached ciphey-3.5.9-py3-none-any.whl (37 kB)
  Using cached Ciphey-3.5.7-py3-none-any.whl (6.2 MB)
Collecting requests-oauthlib==1.3.0
  Using cached requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting absl-py==0.9.0
  Using cached absl-py-0.9.0.tar.gz (104 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-7ka1c8m_/absl-py_d1355793ff694c86b9e59195cb5716ca/setup.py", line 34, in <module>
          raise RuntimeError('Python version 2.7 or 3.4+ is required.')
      RuntimeError: Python version 2.7 or 3.4+ is required.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**To Reproduce**
1. Try to install using pip
2. Fail

**Expected behavior**
Installs ciphey

**Any other information?**
I'm using a virtualenv

**Comment by FalcoGer** [comment]
I use linux. It says python3.9 is fine with other platforms (than windows), so I compiled python 3.9. It doesn't work with python 3.9 on linux (which you just said would work)

**Comment by FalcoGer** [comment]
```text
pip install -U setuptools
Requirement already satisfied: setuptools in ./lib/python3.9/site-packages (59.6.0)
Collecting setuptools
  Using cached setuptools-62.3.4-py3-none-any.whl (1.2 MB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 59.6.0
    Uninstalling setuptools-59.6.0:
      Successfully uninstalled setuptools-59.6.0
Successfully installed setuptools-62.3.4
```
after that it worked. great. thanks!
