### ISSUE TITLE
Python 3.11.3 but "RuntimeError: Python version 2.7 or 3.4+ is required"

### ISSUE THREAD

**Issue by Drjacky** [Ciphey/Ciphey#771]
- [X] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)

**Describe the bug**
My python is 3.11.3 but it still give me an error about minimum requirement!

**Plaintext**
```groovy
Collecting absl-py==0.9.0
  Downloading absl-py-0.9.0.tar.gz (104 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.0/104.0 kB 12.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/4c/13yp5nx15q1_vfhb_cswvjt00000gn/T/pip-install-qrij_u_5/absl-py_2094f04f72674800af50ce154de97249/setup.py", line 34, in <module>
          raise RuntimeError('Python version 2.7 or 3.4+ is required.')
      RuntimeError: Python version 2.7 or 3.4+ is required.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

```
Include your plaintext here, replacing this 
```
**Version**
**⚠️IMPORTANT⚠️ We need this information because different environments will induce different bugs in Ciphey**
 - OS/Distro: [e.g. macOS 13.3.1
 - Python version: 3.11.3
 - Ciphey versions: not able to install it
 - Did you use Docker? No

**Comment by Drjacky** [comment]
It works perfectly with Docker
