### ISSUE TITLE
Python 3.11.2 but "RuntimeError: Python version 2.7 or 3.4+ is required"

### ISSUE THREAD

**Issue by AgentPhoenix7** [Ciphey/Ciphey#774]
**Describe the bug**
 My python is 3.11.2 but it still give me an error about minimum requirement!

**Plaintext**
```
python3 -m pip install -U ciphey          
Defaulting to user installation because normal site-packages is not writeable
Collecting ciphey
  Using cached ciphey-5.14.0-py3-none-any.whl (90 kB)
Requirement already satisfied: appdirs<2.0.0,>=1.4.4 in /usr/lib/python3/dist-packages (from ciphey) (1.4.4)
Collecting base58<3.0.0,>=2.0.1
  Using cached base58-2.1.1-py3-none-any.whl (5.6 kB)
Collecting base91<2.0.0,>=1.0.1
  Using cached base91-1.0.1-py3-none-any.whl (3.4 kB)
Collecting ciphey
  Using cached ciphey-5.13.0-py3-none-any.whl (90 kB)
  Using cached ciphey-5.12.1-py3-none-any.whl (89 kB)
  Using cached ciphey-5.12.0-py3-none-any.whl (89 kB)
  Using cached ciphey-5.11.3-py3-none-any.whl (88 kB)
  Using cached ciphey-5.11.2-py3-none-any.whl (89 kB)
  Using cached ciphey-5.11.1-py3-none-any.whl (89 kB)
  Using cached ciphey-5.10.0-py3-none-any.whl (87 kB)
  Using cached ciphey-5.9.0-py3-none-any.whl (84 kB)
  Using cached ciphey-5.8.0-py3-none-any.whl (77 kB)
  Using cached ciphey-5.7.0-py3-none-any.whl (74 kB)
  Using cached ciphey-5.6.0-py3-none-any.whl (72 kB)
  Using cached ciphey-5.5.3-py3-none-any.whl (70 kB)
  Using cached ciphey-5.5.2-py3-none-any.whl (69 kB)
  Using cached ciphey-5.4.0-py3-none-any.whl (66 kB)
  Using cached ciphey-5.3.2-py3-none-any.whl (58 kB)
  Using cached ciphey-5.3.1-py3-none-any.whl (58 kB)
  Using cached ciphey-5.3.0-py3-none-any.whl (56 kB)
  Using cached ciphey-5.2.0-py3-none-any.whl (54 kB)
  Using cached ciphey-5.1.0-py3-none-any.whl (51 kB)
  Using cached ciphey-5.0.0-py3-none-any.whl (50 kB)
  Using cached ciphey-4.2.1-py3-none-any.whl (38 kB)
  Using cached ciphey-4.2.0-py3-none-any.whl (37 kB)
  Using cached Ciphey-3.8.2-py3-none-any.whl (6.2 MB)
Collecting requests~=2.23.0
  Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
Collecting loguru~=0.5.0
  Using cached loguru-0.5.3-py3-none-any.whl (57 kB)
Collecting rich~=1.2.3
  Using cached rich-1.2.3-py3-none-any.whl (123 kB)
Collecting ciphey
  Using cached Ciphey-3.8.1-py3-none-any.whl (6.2 MB)
  Using cached Ciphey-3.8-py3-none-any.whl (6.2 MB)
  Using cached ciphey-3.5.9-py3-none-any.whl (37 kB)
  Using cached Ciphey-3.5.7-py3-none-any.whl (6.2 MB)
Collecting absl-py==0.9.0
  Using cached absl-py-0.9.0.tar.gz (104 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-00v5fq4t/absl-py_681c439bba724718800024a3bb2289bc/setup.py", line 34, in <module>
          raise RuntimeError('Python version 2.7 or 3.4+ is required.')
      RuntimeError: Python version 2.7 or 3.4+ is required.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
**Version**

 **IMPORTANT We need this information because different environments will induce different bugs in Ciphey**

- OS/Distro: Kali Linux 6.1.0-kali9-amd64 Debian 6.1.27-1kali1 (2023-05-12) x86_64 GNU/Linux
- Python version: 3.11.2
- Ciphey versions: not able to install it
- Did you use Docker? No

**Comment by Jayy001** [comment]
Hi, ciphey doesn't support version 3.11 - check the wiki for further information

**Comment by DoctorPentester** [comment]
> Hi, ciphey doesn't support version 3.11 - check the wiki for further information

Then how to use???

**Comment by Jayy001** [comment]
https://github.com/Ciphey/Ciphey/wiki/Installation

Use a python version that's supported

**Comment by AgentPhoenix7** [comment]
> https://github.com/Ciphey/Ciphey/wiki/Installation
> 
> Use a python version that's supported

Thanks
