### ISSUE TITLE
Ciphey doesn't install on Python 3.8

### ISSUE THREAD

**Issue by DUOLabs333** [Ciphey/Ciphey#779]
**⚠️IMPORTANT⚠️ if you do not fill this out, we will automatically delete your issue. We will not help anyone that cannot fill out this template.**

- [x] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)

**Describe the bug**
If I try to install Ciphey, I get an error when compiling numpy (I'm on arm64, so there aren't packages for that architecture on 3.8).

**Verbose Output**
```
Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'
gfortran libopenblas-dev liblapack-dev
Error compiling Cython file:
    ------------------------------------------------------------
    ...
        def __init__(self, seed=None):
            BitGenerator.__init__(self, seed)
            self.rng_state.pcg_state = &self.pcg64_random_state
    
            self._bitgen.state = <void *>&self.rng_state
            self._bitgen.next_uint64 = &pcg64_uint64
                                       ^
    ------------------------------------------------------------
    
    _pcg64.pyx:113:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'
    /tmp/pip-install-rbsr88b4/numpy_79643cf1003c4723bdfad6c981af55c1/tools/cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
      required_version = LooseVersion('0.29.14')
    /tmp/pip-install-rbsr88b4/numpy_79643cf1003c4723bdfad6c981af55c1/tools/cythonize.py:77: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
      if LooseVersion(cython_version) < required_version:
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/_pcg64.pyx
    Traceback (most recent call last):
      File "/tmp/pip-install-rbsr88b4/numpy_79643cf1003c4723bdfad6c981af55c1/tools/cythonize.py", line 238, in <module>
        main()
      File "/tmp/pip-install-rbsr88b4/numpy_79643cf1003c4723bdfad6c981af55c1/tools/cythonize.py", line 234, in main
        find_process_files(root_dir)
      File "/tmp/pip-install-rbsr88b4/numpy_79643cf1003c4723bdfad6c981af55c1/tools/cythonize.py", line 225, in find_process_files
        process(root_dir, fromfile, tofile, function, hash_db)
      File "/tmp/pip-install-rbsr88b4/numpy_79643cf1003c4723bdfad6c981af55c1/tools/cythonize.py", line 191, in process
        processor_function(fromfile, tofile)
      File "/tmp/pip-install-rbsr88b4/numpy_79643cf1003c4723bdfad6c981af55c1/tools/cythonize.py", line 80, in process_pyx
        subprocess.check_call(
      File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/local/bin/python', '-m', 'cython', '-3', '--fast-fail', '-o', '_pcg64.c', '_pcg64.pyx']' returned non-zero exit status 1.
    Running from numpy source directory.
    <string>:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
    Cythonizing sources
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
        main()
      File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 151, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-ccig7w0h/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 380, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-ccig7w0h/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 487, in run_setup
        super(_BuildMetaLegacyBackend,
      File "/tmp/pip-build-env-ccig7w0h/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
        exec(code, locals())
      File "<string>", line 488, in <module>
      File "<string>", line 469, in setup_package
      File "<string>", line 275, in generate_cython
    RuntimeError: Running cythonize failed!
    ----------------------------------------
```

**To Reproduce**
1. Use Arch Linux ARM
2. Install Python 3.8
3. Try `pip install ciphey`

**Comment by DUOLabs333** [comment]
This is due to the fact that cipheycore does not have source packages, so pip downgraded ciphey to a version where cipheycore does have source packages, leading to the use of an old numpy version (in >=0.19.0, numpy provides ARM wheels). Manually downloading and compiling cipheycore leads to a successful installation of ciphey 5.14.0.

**Comment by DUOLabs333** [comment]
Oh, I don't use ciphey anymore, so I can't help you with that. Try https://github.com/Ciphey/CipheyCore though.
