### ISSUE TITLE
Ciphey not installing with Python 3.11.5

### ISSUE THREAD

**Issue by NodeRaven** [Ciphey/Ciphey#786]
Trying to install Ciphey with Python3.11 provides errors. Is it supported?

**Kali Linux (6.5.0-kali1-amd64)**

**Python 3.11.5**

```
_python3 -m pip install -U ciphey_
Defaulting to user installation because normal site-packages is not writeable
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/mitm6-0.3.0-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
Collecting ciphey
  Using cached ciphey-5.14.0-py3-none-any.whl (90 kB)
Requirement already satisfied: appdirs<2.0.0,>=1.4.4 in /usr/lib/python3/dist-packages (from ciphey) (1.4.4)
Collecting base58<3.0.0,>=2.0.1 (from ciphey)
  Using cached base58-2.1.1-py3-none-any.whl (5.6 kB)
Collecting base91<2.0.0,>=1.0.1 (from ciphey)
  Using cached base91-1.0.1-py3-none-any.whl (3.4 kB)
INFO: pip is looking at multiple versions of ciphey to determine which version is compatible with other requirements. This could take a while.
Collecting ciphey
  Using cached ciphey-5.13.0-py3-none-any.whl (90 kB)
  Using cached ciphey-5.12.1-py3-none-any.whl (89 kB)
  Using cached ciphey-5.12.0-py3-none-any.whl (89 kB)
  Using cached ciphey-5.11.3-py3-none-any.whl (88 kB)
  Using cached ciphey-5.11.2-py3-none-any.whl (89 kB)
  Using cached ciphey-5.11.1-py3-none-any.whl (89 kB)
  Using cached ciphey-5.10.0-py3-none-any.whl (87 kB)
INFO: pip is still looking at multiple versions of ciphey to determine which version is compatible with other requirements. This could take a while.
  Using cached ciphey-5.9.0-py3-none-any.whl (84 kB)
  Using cached ciphey-5.8.0-py3-none-any.whl (77 kB)
  Using cached ciphey-5.7.0-py3-none-any.whl (74 kB)
  Using cached ciphey-5.6.0-py3-none-any.whl (72 kB)
  Using cached ciphey-5.5.3-py3-none-any.whl (70 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached ciphey-5.5.2-py3-none-any.whl (69 kB)
  Using cached ciphey-5.4.0-py3-none-any.whl (66 kB)
  Using cached ciphey-5.3.2-py3-none-any.whl (58 kB)
  Using cached ciphey-5.3.1-py3-none-any.whl (58 kB)
  Using cached ciphey-5.3.0-py3-none-any.whl (56 kB)
  Using cached ciphey-5.2.0-py3-none-any.whl (54 kB)
  Using cached ciphey-5.1.0-py3-none-any.whl (51 kB)
  Using cached ciphey-5.0.0-py3-none-any.whl (50 kB)
  Using cached ciphey-4.2.1-py3-none-any.whl (38 kB)
  Using cached ciphey-4.2.0-py3-none-any.whl (37 kB)
  Using cached Ciphey-3.8.2-py3-none-any.whl (6.2 MB)
Collecting requests~=2.23.0 (from ciphey)
  Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
Collecting loguru~=0.5.0 (from ciphey)
  Using cached loguru-0.5.3-py3-none-any.whl (57 kB)
Collecting rich~=1.2.3 (from ciphey)
  Using cached rich-1.2.3-py3-none-any.whl (123 kB)
Collecting ciphey
  Using cached Ciphey-3.8.1-py3-none-any.whl (6.2 MB)
  Using cached Ciphey-3.8-py3-none-any.whl (6.2 MB)
  Using cached ciphey-3.5.9-py3-none-any.whl (37 kB)
  Using cached Ciphey-3.5.7-py3-none-any.whl (6.2 MB)
Collecting absl-py==0.9.0 (from ciphey)
  Using cached absl-py-0.9.0.tar.gz (104 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-23atcx21/absl-py_7f745d35e7194f39a3859ba7683e3b31/setup.py", line 34, in <module>
          raise RuntimeError('Python version 2.7 or 3.4+ is required.')
      RuntimeError: Python version 2.7 or 3.4+ is required.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by slaee** [comment]
same

**Comment by DrEldonTyrell** [comment]
same

**Comment by Jayy001** [comment]
https://github.com/Ciphey/Ciphey/wiki/Installation

No it's not supported

**Comment by CamsShaft** [comment]
Just tried to install and got 20 lines of output. That sucks, was looking forward to something hopeful that works with android 13. Perhaps it could be rebuilt and upgraded?

**Comment by 1000goalgaming** [comment]
Same problem

**Comment by SkeletalDemise** [comment]
Python 3.11 is not supported. Here is the installation guide: https://github.com/Ciphey/Ciphey/wiki/Installation

Additionally, we are not working on Ciphey anymore. We are remaking Ciphey in Rust due to numerous reasons.
https://github.com/Ciphey/Ciphey/issues/764

**Comment by ACyouth** [comment]
the maybe reason: Due to a bug in string comparison, when checking the Python version, it compares each character individually ('4' > '1'), thus "4" is considered greater than "10".
