### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by Lynka7** [Ciphey/Ciphey#789]
Collecting absl-py==0.9.0 (from ciphey)
  Using cached absl-py-0.9.0.tar.gz (104 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-y88sbzvc/absl-py_822b230fed0f4e07a862a440274b4c3a/setup.py", line 34, in <module>
          raise RuntimeError('Python version 2.7 or 3.4+ is required.')
      RuntimeError: Python version 2.7 or 3.4+ is required.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by ADI-TECH-API** [comment]
i have same issue :(

**Comment by francogrex** [comment]
That's because you are using python 3.10+. Use python 3.7, 3.8 and if you're lucky 3.9

**Comment by alfred-hong** [comment]
<pre>  Preparing metadata (setup.py) ... error
  <span style="color:#C01C28"><b>error</b></span>: <b>subprocess-exited-with-error</b>
  
  <span style="color:#C01C28">×</span> <span style="color:#26A269">python setup.py egg_info</span> did not run successfully.
  <span style="color:#C01C28">│</span> exit code: <span style="color:#2AA1B3"><b>1</b></span>
  <span style="color:#C01C28">╰─&gt;</span> <span style="color:#C01C28">[6 lines of output]</span>
  <span style="color:#C01C28">   </span> Traceback (most recent call last):
  <span style="color:#C01C28">   </span>   File &quot;&lt;string&gt;&quot;, line 2, in &lt;module&gt;
  <span style="color:#C01C28">   </span>   File &quot;&lt;pip-setuptools-caller&gt;&quot;, line 34, in &lt;module&gt;
  <span style="color:#C01C28">   </span>   File &quot;/tmp/pip-install-bk5uj744/absl-py_977fda649ecc4a9099fbf71b380f98f3/setup.py&quot;, line 34, in &lt;module&gt;
  <span style="color:#C01C28">   </span>     raise RuntimeError(&apos;Python version 2.7 or 3.4+ is required.&apos;)
  <span style="color:#C01C28">   </span> RuntimeError: Python version 2.7 or 3.4+ is required.
  <span style="color:#C01C28">   </span> <span style="color:#C01C28">[end of output]</span>
  
  <span style="color:#A347BA"><b>note</b></span>: This error originates from a subprocess, and is likely not a problem with pip.
<span style="color:#C01C28"><b>error</b></span>: <b>metadata-generation-failed</b>

<span style="color:#C01C28">×</span> Encountered error while generating package metadata.
<span style="color:#C01C28">╰─&gt;</span> See above for output.
</pre>


the same

**Comment by ZishanAdThandar** [comment]
> That's because you are using python 3.10+. Use python 3.7, 3.8 and if you're lucky 3.9

Why??
and how to install it on Python 3.10+??? any solution

**Comment by ZishanAdThandar** [comment]
#786 Ciphey not installing with Python 3.11.5
#764 Ciphey is being deprecated

They are remaking it currently with rust on https://github.com/bee-san/Ares to resolve all issues.

**Comment by SyKaHo** [comment]
how i can slove this(mac os)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/ciphey", line 5, in <module>
    from ciphey.ciphey import main
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ciphey/__init__.py", line 1, in <module>
    from . import basemods, common, iface
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ciphey/basemods/__init__.py", line 1, in <module>
    from . import Checkers, Crackers, Decoders, Resources, Searchers
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ciphey/basemods/Crackers/__init__.py", line 1, in <module>
    from . import (
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ciphey/basemods/Crackers/affine.py", line 6, in <module>
    import cipheycore
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cipheycore/__init__.py", line 13, in <module>
    from . import _ciphey_core_py
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cipheycore/_ciphey_core_py.so, 0x0002): Library not loaded: /usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/Python
  Referenced from: <5DF0F2B7-C780-33C3-A619-97D7F363AA91> /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cipheycore/_ciphey_core_py.so
  Reason: tried: '/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/Python' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/Python' (no such file), '/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/Python' (no such file), '/System/Library/Frameworks/Python.framework/Versions/3.8/Python' (no such file, not in dyld cache)

**Comment by 0x5869616F** [comment]
Same error, my python environment is 3.11：
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-85quaiwz/absl-py_bd08e1ef554348d6bcb1bb07f825e0b4/setup.py", line 34, in <module>
          raise RuntimeError('Python version 2.7 or 3.4+ is required.')
      RuntimeError: Python version 2.7 or 3.4+ is required.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by 2421715443** [comment]
[https://github.com/abseil/abseil-py/blob/pypi-v0.9.0/setup.py](absl-py setup.py(absl-py==0.9.0))
this version is 
```
py_version = platform.python_version_tuple()
if py_version < ('2', '7') or py_version[0] == '3' and py_version < ('3', '4'):
  raise RuntimeError('Python version 2.7 or 3.4+ is required.')
```
platform.python_version_tuple() get a str tuple

**Comment by HoveyChenB612** [comment]
me tooooooo :(
```shell
error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/Users/chen/VScodeProjects/Tooles/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/chen/VScodeProjects/Tooles/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/chen/VScodeProjects/Tooles/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/xm/65v1lvj912l988bmm_hk_wmc0000gn/T/pip-build-env-dtyiowqd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/xm/65v1lvj912l988bmm_hk_wmc0000gn/T/pip-build-env-dtyiowqd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/xm/65v1lvj912l988bmm_hk_wmc0000gn/T/pip-build-env-dtyiowqd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/xm/65v1lvj912l988bmm_hk_wmc0000gn/T/pip-build-env-dtyiowqd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 34, in <module>
      RuntimeError: Python version 2.7 or 3.4+ is required.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
