### ISSUE TITLE
Console output error

### ISSUE THREAD

**Issue by 2622594863** [Ciphey/Ciphey#795]
ciphey -t "NTIxNjE1Ng=="

UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 695: illegal multibyte sequence

**Comment by Liber1917** [comment]
The same error, the console info below:
```
(web_ciphey) PS D:\CTF\Web\web_ciphey> ciphey -t "aGVsbG8gbXkgbmFtZSBpcyBiZWU="
Traceback (most recent call last):
  File "C:\Users\Mlegi\.version-fox\cache\python\v-3.7.4\python-3.7.4\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Mlegi\.version-fox\cache\python\v-3.7.4\python-3.7.4\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\CTF\Web\web_ciphey\Scripts\ciphey.exe\__main__.py", line 9, in <module>
  File "d:\ctf\web\web_ciphey\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "d:\ctf\web\web_ciphey\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "d:\ctf\web\web_ciphey\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\ctf\web\web_ciphey\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\ciphey.py", line 222, in main
    config.complete_config()
  File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\iface\_config.py", line 189, in complete_config
    self.load_objs()
  File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\iface\_config.py", line 132, in load_objs
    _fwd.registry.get_named(self.checker, PolymorphicChecker)
  File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\iface\_config.py", line 102, in __call__
    return self.instantiate(t)
  File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\iface\_config.py", line 97, in instantiate
    ret = t(self)
  File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\iface\_modules.py", line 153, in __init__
    self._base = cls(config)
  File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\basemods\Checkers\ezcheck.py", line 46, in __init__
    self.checkers.append(config(What))
  File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\iface\_config.py", line 102, in __call__
    return self.instantiate(t)
  File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\iface\_config.py", line 97, in instantiate
    ret = t(self)
  File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\iface\_modules.py", line 153, in __init__
    self._base = cls(config)
  File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\basemods\Checkers\what.py", line 59, in __init__
    self.id = identifier.Identifier()
  File "d:\ctf\web\web_ciphey\lib\site-packages\pywhat\identifier.py", line 10, in __init__
    self.regex_id = RegexIdentifier()
  File "d:\ctf\web\web_ciphey\lib\site-packages\pywhat\regex_identifier.py", line 11, in __init__
    self.regexes = json.load(myfile)
  File "C:\Users\Mlegi\.version-fox\cache\python\v-3.7.4\python-3.7.4\lib\json\__init__.py", line 298, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 695: illegal multibyte sequence
```

**Comment by 2622594863** [comment]
> The same error, the console info below:
> 
> ```
> (web_ciphey) PS D:\CTF\Web\web_ciphey> ciphey -t "aGVsbG8gbXkgbmFtZSBpcyBiZWU="
> Traceback (most recent call last):
>   File "C:\Users\Mlegi\.version-fox\cache\python\v-3.7.4\python-3.7.4\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "C:\Users\Mlegi\.version-fox\cache\python\v-3.7.4\python-3.7.4\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "D:\CTF\Web\web_ciphey\Scripts\ciphey.exe\__main__.py", line 9, in <module>
>   File "d:\ctf\web\web_ciphey\lib\site-packages\click\core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "d:\ctf\web\web_ciphey\lib\site-packages\click\core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "d:\ctf\web\web_ciphey\lib\site-packages\click\core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "d:\ctf\web\web_ciphey\lib\site-packages\click\core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\ciphey.py", line 222, in main
>     config.complete_config()
>   File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\iface\_config.py", line 189, in complete_config
>     self.load_objs()
>   File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\iface\_config.py", line 132, in load_objs
>     _fwd.registry.get_named(self.checker, PolymorphicChecker)
>   File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\iface\_config.py", line 102, in __call__
>     return self.instantiate(t)
>   File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\iface\_config.py", line 97, in instantiate
>     ret = t(self)
>   File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\iface\_modules.py", line 153, in __init__
>     self._base = cls(config)
>   File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\basemods\Checkers\ezcheck.py", line 46, in __init__
>     self.checkers.append(config(What))
>   File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\iface\_config.py", line 102, in __call__
>     return self.instantiate(t)
>   File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\iface\_config.py", line 97, in instantiate
>     ret = t(self)
>   File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\iface\_modules.py", line 153, in __init__
>     self._base = cls(config)
>   File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\basemods\Checkers\what.py", line 59, in __init__
>     self.id = identifier.Identifier()
>   File "d:\ctf\web\web_ciphey\lib\site-packages\pywhat\identifier.py", line 10, in __init__
>     self.regex_id = RegexIdentifier()
>   File "d:\ctf\web\web_ciphey\lib\site-packages\pywhat\regex_identifier.py", line 11, in __init__
>     self.regexes = json.load(myfile)
>   File "C:\Users\Mlegi\.version-fox\cache\python\v-3.7.4\python-3.7.4\lib\json\__init__.py", line 298, in load
>     return loads(fp.read(),
> UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 695: illegal multibyte sequence
> ```
I successfully ran this project in docker

**Comment by Liber1917** [comment]
> > The same error, the console info below:
> > 
> > ```
> > (web_ciphey) PS D:\CTF\Web\web_ciphey> ciphey -t "aGVsbG8gbXkgbmFtZSBpcyBiZWU="
> > Traceback (most recent call last):
> >   File "C:\Users\Mlegi\.version-fox\cache\python\v-3.7.4\python-3.7.4\lib\runpy.py", line 193, in _run_module_as_main
> >     "__main__", mod_spec)
> >   File "C:\Users\Mlegi\.version-fox\cache\python\v-3.7.4\python-3.7.4\lib\runpy.py", line 85, in _run_code
> >     exec(code, run_globals)
> >   File "D:\CTF\Web\web_ciphey\Scripts\ciphey.exe\__main__.py", line 9, in <module>
> >   File "d:\ctf\web\web_ciphey\lib\site-packages\click\core.py", line 1157, in __call__
> >     return self.main(*args, **kwargs)
> >   File "d:\ctf\web\web_ciphey\lib\site-packages\click\core.py", line 1078, in main
> >     rv = self.invoke(ctx)
> >   File "d:\ctf\web\web_ciphey\lib\site-packages\click\core.py", line 1434, in invoke
> >     return ctx.invoke(self.callback, **ctx.params)
> >   File "d:\ctf\web\web_ciphey\lib\site-packages\click\core.py", line 783, in invoke
> >     return __callback(*args, **kwargs)
> >   File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\ciphey.py", line 222, in main
> >     config.complete_config()
> >   File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\iface\_config.py", line 189, in complete_config
> >     self.load_objs()
> >   File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\iface\_config.py", line 132, in load_objs
> >     _fwd.registry.get_named(self.checker, PolymorphicChecker)
> >   File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\iface\_config.py", line 102, in __call__
> >     return self.instantiate(t)
> >   File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\iface\_config.py", line 97, in instantiate
> >     ret = t(self)
> >   File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\iface\_modules.py", line 153, in __init__
> >     self._base = cls(config)
> >   File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\basemods\Checkers\ezcheck.py", line 46, in __init__
> >     self.checkers.append(config(What))
> >   File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\iface\_config.py", line 102, in __call__
> >     return self.instantiate(t)
> >   File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\iface\_config.py", line 97, in instantiate
> >     ret = t(self)
> >   File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\iface\_modules.py", line 153, in __init__
> >     self._base = cls(config)
> >   File "d:\ctf\web\web_ciphey\lib\site-packages\ciphey\basemods\Checkers\what.py", line 59, in __init__
> >     self.id = identifier.Identifier()
> >   File "d:\ctf\web\web_ciphey\lib\site-packages\pywhat\identifier.py", line 10, in __init__
> >     self.regex_id = RegexIdentifier()
> >   File "d:\ctf\web\web_ciphey\lib\site-packages\pywhat\regex_identifier.py", line 11, in __init__
> >     self.regexes = json.load(myfile)
> >   File "C:\Users\Mlegi\.version-fox\cache\python\v-3.7.4\python-3.7.4\lib\json\__init__.py", line 298, in load
> >     return loads(fp.read(),
> > UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 695: illegal multibyte sequence
> > ```
> I successfully ran this project in docker
> 

但是鼠鼠的surface内存有限捏
