### ISSUE TITLE
Installation error via pip

### ISSUE THREAD

**Issue by trevzhang** [Ciphey/Ciphey#796]
**⚠️IMPORTANT⚠️ if you do not fill this out, we will automatically delete your issue. We will not help anyone that cannot fill out this template.**

- ✅ Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)

**Describe the bug**

$ python --version                                                                         
Python 3.8.18

$ python3 -m pip install ciphey --upgrade
...(installing dependencies)
Collecting numpy==1.18.4 (from ciphey)
  Using cached numpy-1.18.4.zip (5.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  self.rng_state.ctr.v[i] = counter[i]
      
              self._reset_state_variables()
      
              self._bitgen.state = <void *>&self.rng_state
              self._bitgen.next_uint64 = &philox_uint64
                                         ^
      ------------------------------------------------------------
      
      _philox.pyx:195:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to the type of the value being assigned.
      /private/var/folders/xg/7fs395h909jf8hzr2lvstxpc0000gn/T/pip-install-5rn44_zq/numpy_21a8dec874a44e909e471b48086068a7/tools/cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        required_version = LooseVersion('0.29.14')
      /private/var/folders/xg/7fs395h909jf8hzr2lvstxpc0000gn/T/pip-install-5rn44_zq/numpy_21a8dec874a44e909e471b48086068a7/tools/cythonize.py:77: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(cython_version) < required_version:
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_philox.pyx
      Traceback (most recent call last):
        File "/private/var/folders/xg/7fs395h909jf8hzr2lvstxpc0000gn/T/pip-install-5rn44_zq/numpy_21a8dec874a44e909e471b48086068a7/tools/cythonize.py", line 238, in <module>
          main()
        File "/private/var/folders/xg/7fs395h909jf8hzr2lvstxpc0000gn/T/pip-install-5rn44_zq/numpy_21a8dec874a44e909e471b48086068a7/tools/cythonize.py", line 234, in main
          find_process_files(root_dir)
        File "/private/var/folders/xg/7fs395h909jf8hzr2lvstxpc0000gn/T/pip-install-5rn44_zq/numpy_21a8dec874a44e909e471b48086068a7/tools/cythonize.py", line 225, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "/private/var/folders/xg/7fs395h909jf8hzr2lvstxpc0000gn/T/pip-install-5rn44_zq/numpy_21a8dec874a44e909e471b48086068a7/tools/cythonize.py", line 191, in process
          processor_function(fromfile, tofile)
        File "/private/var/folders/xg/7fs395h909jf8hzr2lvstxpc0000gn/T/pip-install-5rn44_zq/numpy_21a8dec874a44e909e471b48086068a7/tools/cythonize.py", line 80, in process_pyx
          subprocess.check_call(
        File "/Users/zcg/anaconda3/envs/python38/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Users/zcg/anaconda3/envs/python38/bin/python3', '-m', 'cython', '-3', '--fast-fail', '-o', '_philox.c', '_philox.pyx']' returned non-zero exit status 1.
      Running from numpy source directory.
      <string>:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      Cythonizing sources
      Traceback (most recent call last):
        File "/Users/zcg/anaconda3/envs/python38/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/zcg/anaconda3/envs/python38/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/zcg/anaconda3/envs/python38/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/xg/7fs395h909jf8hzr2lvstxpc0000gn/T/pip-build-env-17cc4an6/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/xg/7fs395h909jf8hzr2lvstxpc0000gn/T/pip-build-env-17cc4an6/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/xg/7fs395h909jf8hzr2lvstxpc0000gn/T/pip-build-env-17cc4an6/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 488, in <module>
        File "<string>", line 469, in setup_package
        File "<string>", line 275, in generate_cython
      RuntimeError: Running cythonize failed!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by BenYang66** [comment]
Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "D:\python\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\python\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\python\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-p4u1pexk\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-p4u1pexk\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-p4u1pexk\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-p4u1pexk\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 34, in <module>
      RuntimeError: Python version 2.7 or 3.4+ is required.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

**Comment by Letgamer** [comment]
I got the same error running Python 3.11.8 on Kali Linux

**Comment by ahackercalled4chan** [comment]
i got this as well. had to just run the example command  # ciphey -t "aGVsbG8gbXkgbmFtZSBpcyBiZWU=" 
and got an error with a prompt to install via a non-pip method. that seems to work, but it gets stuck if the cypher is more than 3 layers deep (similar to issue 300 https://github.com/Ciphey/Ciphey/issues/300)

**Comment by ThomasNoSimp** [comment]
Same, it is also happening to me.

**Comment by ahackercalled4chan** [comment]
> Same, it is also happening to me.

some other message boards have said that Ciphey is deprecated and to use Project Ares instead (not to be confused with Ares emulator)

https://github.com/bee-san/Ares
